// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.3.6
// Machine:  DESKTOP-56159VE
// DateTime: 29.09.2024 11:25:50
// UserName: ????
// Input file <SPythonParser.y>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using PascalABCCompiler.SyntaxTree;
using PascalABCCompiler.ParserTools;
using PascalABCCompiler.Errors;
using System.Linq;
using System.Collections.Generic;
using System.IO;
using SPythonParser;

namespace SPythonParserYacc
{
public enum Tokens {
    error=1,EOF=2,FOR=3,IN=4,WHILE=5,IF=6,
    ELSE=7,ELIF=8,DEF=9,RETURN=10,BREAK=11,CONTINUE=12,
    IMPORT=13,FROM=14,GLOBAL=15,INTNUM=16,REALNUM=17,TRUE=18,
    FALSE=19,LPAR=20,RPAR=21,LBRACE=22,RBRACE=23,LBRACKET=24,
    RBRACKET=25,DOT=26,COMMA=27,COLON=28,SEMICOLON=29,INDENT=30,
    UNINDENT=31,ARROW=32,STRINGNUM=33,ASSIGN=34,PLUSEQUAL=35,MINUSEQUAL=36,
    STAREQUAL=37,DIVEQUAL=38,PLUS=39,MINUS=40,STAR=41,DIVIDE=42,
    SLASHSLASH=43,PERCENTAGE=44,ID=45,LESS=46,GREATER=47,LESSEQUAL=48,
    GREATEREQUAL=49,EQUAL=50,NOTEQUAL=51,AND=52,OR=53,NOT=54};

public partial struct ValueType
{
	public expression ex;
	public ident id;
    public Object ob;
    public op_type_node op;
    public syntax_tree_node stn;
    public token_info ti;
    public type_definition td;
}
// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

public partial class SPythonGPPGParser: ShiftReduceParser<ValueType, LexLocation>
{
  // Verbatim content from SPythonParser.y
   	public syntax_tree_node root;
	public List<Error> errors;
    // public string current_file_name;
    // public int max_errors = 10;
	public SPythonParserTools parserTools;
    public List<compiler_directive> CompilerDirectives;
	public ParserLambdaHelper lambdaHelper = new ParserLambdaHelper();

	private SymbolTable symbolTable = new SymbolTable();
	private SymbolTable globalVariables = new SymbolTable();
	private declarations decl_forward = new declarations();
	private declarations decl = new declarations();
	private bool isInsideFunction = false;
	private bool isVariableToBeAssigned = false;

	public bool is_unit_to_be_parsed = false;

	public SPythonGPPGParser(AbstractScanner<ValueType, LexLocation> scanner, SPythonParserTools parserTools,
	bool isUnitToBeParsed) : base(scanner) 
	{ 
		this.parserTools = parserTools;
		this.is_unit_to_be_parsed = isUnitToBeParsed;
	}
  // End verbatim content from SPythonParser.y

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[114];
  private static State[] states = new State[193];
  private static string[] nonTerms = new string[] {
      "ident", "dotted_ident", "range_ident", "func_name_ident", "expr", "proc_func_call", 
      "const_value", "complex_variable", "variable", "complex_variable_or_ident", 
      "optional_condition", "act_param", "act_param_list", "optional_act_param_list", 
      "proc_func_decl", "return_stmt", "break_stmt", "continue_stmt", "global_stmt", 
      "var_stmt", "assign_stmt", "if_stmt", "stmt", "proc_func_call_stmt", "while_stmt", 
      "for_stmt", "optional_else", "optional_elif", "decl_or_stmt", "decl_and_stmt_list", 
      "expr_list", "stmt_list", "block", "program", "decl", "param_name", "form_param_sect", 
      "form_param_list", "optional_form_param_list", "dotted_ident_list", "proc_func_header", 
      "form_param_type", "simple_type_identifier", "import_clause", "import_clause_one", 
      "optional_semicolon", "assign_type", "$accept", "NestedSymbolTableBegin", 
      "NestedSymbolTableEnd", "InsideFunction", "OutsideFunction", };

  static SPythonGPPGParser() {
    states[0] = new State(-3,new int[]{-34,1,-44,3});
    states[1] = new State(new int[]{2,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{45,59,16,69,17,70,18,71,19,72,33,73,24,74,6,109,5,132,3,137,10,145,11,148,12,150,15,152,13,190,9,-90},new int[]{-30,4,-45,188,-29,189,-23,8,-21,9,-9,10,-1,103,-8,104,-6,105,-10,60,-7,106,-20,107,-22,108,-24,130,-25,131,-26,136,-16,144,-17,147,-18,149,-19,151,-35,161,-15,162,-49,163});
    states[4] = new State(new int[]{29,6,2,-113},new int[]{-46,5});
    states[5] = new State(-2);
    states[6] = new State(new int[]{45,59,16,69,17,70,18,71,19,72,33,73,24,74,6,109,5,132,3,137,10,145,11,148,12,150,15,152,2,-112,9,-90},new int[]{-29,7,-23,8,-21,9,-9,10,-1,103,-8,104,-6,105,-10,60,-7,106,-20,107,-22,108,-24,130,-25,131,-26,136,-16,144,-17,147,-18,149,-19,151,-35,161,-15,162,-49,163});
    states[7] = new State(-10);
    states[8] = new State(-6);
    states[9] = new State(-13);
    states[10] = new State(new int[]{34,11,20,48,28,94,35,99,36,100,37,101,38,102},new int[]{-47,92});
    states[11] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,12,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[12] = new State(new int[]{39,13,41,15,42,17,40,19,46,21,47,23,48,25,49,27,50,29,51,31,52,33,53,35,43,37,44,39,29,-30,2,-30});
    states[13] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,14,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[14] = new State(new int[]{39,-36,41,15,42,17,40,-36,46,-36,47,-36,48,-36,49,-36,50,-36,51,-36,52,-36,53,-36,43,37,44,39,29,-36,2,-36,27,-36,21,-36,25,-36,3,-36,6,-36,28,-36});
    states[15] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,16,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[16] = new State(-37);
    states[17] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,18,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[18] = new State(-38);
    states[19] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,20,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[20] = new State(new int[]{39,-39,41,15,42,17,40,-39,46,-39,47,-39,48,-39,49,-39,50,-39,51,-39,52,-39,53,-39,43,37,44,39,29,-39,2,-39,27,-39,21,-39,25,-39,3,-39,6,-39,28,-39});
    states[21] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,22,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[22] = new State(new int[]{39,13,41,15,42,17,40,19,46,-40,47,-40,48,-40,49,-40,50,-40,51,-40,52,-40,53,-40,43,37,44,39,29,-40,2,-40,27,-40,21,-40,25,-40,3,-40,6,-40,28,-40});
    states[23] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,24,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[24] = new State(new int[]{39,13,41,15,42,17,40,19,46,-41,47,-41,48,-41,49,-41,50,-41,51,-41,52,-41,53,-41,43,37,44,39,29,-41,2,-41,27,-41,21,-41,25,-41,3,-41,6,-41,28,-41});
    states[25] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,26,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[26] = new State(new int[]{39,13,41,15,42,17,40,19,46,-42,47,-42,48,-42,49,-42,50,-42,51,-42,52,-42,53,-42,43,37,44,39,29,-42,2,-42,27,-42,21,-42,25,-42,3,-42,6,-42,28,-42});
    states[27] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,28,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[28] = new State(new int[]{39,13,41,15,42,17,40,19,46,-43,47,-43,48,-43,49,-43,50,-43,51,-43,52,-43,53,-43,43,37,44,39,29,-43,2,-43,27,-43,21,-43,25,-43,3,-43,6,-43,28,-43});
    states[29] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,30,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[30] = new State(new int[]{39,13,41,15,42,17,40,19,46,-44,47,-44,48,-44,49,-44,50,-44,51,-44,52,-44,53,-44,43,37,44,39,29,-44,2,-44,27,-44,21,-44,25,-44,3,-44,6,-44,28,-44});
    states[31] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,32,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[32] = new State(new int[]{39,13,41,15,42,17,40,19,46,-45,47,-45,48,-45,49,-45,50,-45,51,-45,52,-45,53,-45,43,37,44,39,29,-45,2,-45,27,-45,21,-45,25,-45,3,-45,6,-45,28,-45});
    states[33] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,34,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[34] = new State(new int[]{39,13,41,15,42,17,40,19,46,21,47,23,48,25,49,27,50,29,51,31,52,-46,53,-46,43,37,44,39,29,-46,2,-46,27,-46,21,-46,25,-46,3,-46,6,-46,28,-46});
    states[35] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,36,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[36] = new State(new int[]{39,13,41,15,42,17,40,19,46,21,47,23,48,25,49,27,50,29,51,31,52,33,53,-47,43,37,44,39,29,-47,2,-47,27,-47,21,-47,25,-47,3,-47,6,-47,28,-47});
    states[37] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,38,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[38] = new State(-48);
    states[39] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,40,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[40] = new State(-49);
    states[41] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,42,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[42] = new State(new int[]{39,-50,41,15,42,17,40,-50,46,-50,47,-50,48,-50,49,-50,50,-50,51,-50,52,-50,53,-50,43,37,44,39,29,-50,2,-50,27,-50,21,-50,25,-50,3,-50,6,-50,28,-50});
    states[43] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,44,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[44] = new State(-51);
    states[45] = new State(new int[]{39,-52,41,-52,42,-52,40,-52,46,-52,47,-52,48,-52,49,-52,50,-52,51,-52,52,-52,53,-52,43,-52,44,-52,29,-52,2,-52,27,-52,21,-52,25,-52,3,-52,6,-52,28,-52,20,-78,26,-88,24,-88});
    states[46] = new State(-79);
    states[47] = new State(new int[]{20,48});
    states[48] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79,21,-111},new int[]{-14,49,-13,51,-12,91,-5,54,-8,45,-6,46,-9,47,-1,55,-10,60,-7,66});
    states[49] = new State(new int[]{21,50});
    states[50] = new State(-97);
    states[51] = new State(new int[]{27,52,21,-110});
    states[52] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-12,53,-5,54,-8,45,-6,46,-9,47,-1,55,-10,60,-7,66});
    states[53] = new State(-109);
    states[54] = new State(new int[]{39,13,41,15,42,17,40,19,46,21,47,23,48,25,49,27,50,29,51,31,52,33,53,35,43,37,44,39,27,-106,21,-106});
    states[55] = new State(new int[]{34,56,20,-77,26,-87,24,-87,39,-55,41,-55,42,-55,40,-55,46,-55,47,-55,48,-55,49,-55,50,-55,51,-55,52,-55,53,-55,43,-55,44,-55,27,-55,21,-55});
    states[56] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,57,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[57] = new State(new int[]{39,13,41,15,42,17,40,19,46,21,47,23,48,25,49,27,50,29,51,31,52,33,53,35,43,37,44,39,27,-107,21,-107});
    states[58] = new State(new int[]{20,-77,26,-87,24,-87,39,-55,41,-55,42,-55,40,-55,46,-55,47,-55,48,-55,49,-55,50,-55,51,-55,52,-55,53,-55,43,-55,44,-55,29,-55,2,-55,27,-55,21,-55,25,-55,3,-55,6,-55,28,-55});
    states[59] = new State(-24);
    states[60] = new State(new int[]{26,61,24,63});
    states[61] = new State(new int[]{45,59},new int[]{-1,62});
    states[62] = new State(-80);
    states[63] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,64,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[64] = new State(new int[]{25,65,39,13,41,15,42,17,40,19,46,21,47,23,48,25,49,27,50,29,51,31,52,33,53,35,43,37,44,39});
    states[65] = new State(-83);
    states[66] = new State(new int[]{26,67,39,-53,41,-53,42,-53,40,-53,46,-53,47,-53,48,-53,49,-53,50,-53,51,-53,52,-53,53,-53,43,-53,44,-53,29,-53,2,-53,27,-53,21,-53,25,-53,3,-53,6,-53,28,-53});
    states[67] = new State(new int[]{45,59},new int[]{-1,68});
    states[68] = new State(-81);
    states[69] = new State(-56);
    states[70] = new State(-57);
    states[71] = new State(-58);
    states[72] = new State(-59);
    states[73] = new State(-60);
    states[74] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-31,75,-5,82,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[75] = new State(new int[]{25,76,27,77});
    states[76] = new State(-82);
    states[77] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,78,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[78] = new State(new int[]{39,13,41,15,42,17,40,19,46,21,47,23,48,25,49,27,50,29,51,31,52,33,53,35,43,37,44,39,25,-62,27,-62});
    states[79] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,80,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[80] = new State(new int[]{21,81,39,13,41,15,42,17,40,19,46,21,47,23,48,25,49,27,50,29,51,31,52,33,53,35,43,37,44,39});
    states[81] = new State(-54);
    states[82] = new State(new int[]{3,83,39,13,41,15,42,17,40,19,46,21,47,23,48,25,49,27,50,29,51,31,52,33,53,35,43,37,44,39,25,-61,27,-61});
    states[83] = new State(new int[]{45,59},new int[]{-1,84});
    states[84] = new State(new int[]{4,85});
    states[85] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,86,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[86] = new State(new int[]{39,13,41,15,42,17,40,19,46,21,47,23,48,25,49,27,50,29,51,31,52,33,53,35,43,37,44,39,6,89,25,-85},new int[]{-11,87});
    states[87] = new State(new int[]{25,88});
    states[88] = new State(-84);
    states[89] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,90,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[90] = new State(new int[]{39,13,41,15,42,17,40,19,46,21,47,23,48,25,49,27,50,29,51,31,52,33,53,35,43,37,44,39,25,-86});
    states[91] = new State(-108);
    states[92] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,93,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[93] = new State(new int[]{39,13,41,15,42,17,40,19,46,21,47,23,48,25,49,27,50,29,51,31,52,33,53,35,43,37,44,39,29,-31,2,-31});
    states[94] = new State(new int[]{45,59},new int[]{-43,95,-1,98});
    states[95] = new State(new int[]{34,96});
    states[96] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,97,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[97] = new State(new int[]{39,13,41,15,42,17,40,19,46,21,47,23,48,25,49,27,50,29,51,31,52,33,53,35,43,37,44,39,29,-29,2,-29});
    states[98] = new State(-98);
    states[99] = new State(-32);
    states[100] = new State(-33);
    states[101] = new State(-34);
    states[102] = new State(-35);
    states[103] = new State(new int[]{34,-77,20,-77,28,-77,35,-77,36,-77,37,-77,38,-77,26,-87,24,-87});
    states[104] = new State(new int[]{34,-78,20,-78,28,-78,35,-78,36,-78,37,-78,38,-78,26,-88,24,-88});
    states[105] = new State(new int[]{34,-79,20,-79,28,-79,35,-79,36,-79,37,-79,38,-79,26,-79,24,-79,29,-76,2,-76});
    states[106] = new State(new int[]{26,67});
    states[107] = new State(-14);
    states[108] = new State(-15);
    states[109] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,110,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[110] = new State(new int[]{28,111,39,13,41,15,42,17,40,19,46,21,47,23,48,25,49,27,50,29,51,31,52,33,53,35,43,37,44,39});
    states[111] = new State(-90,new int[]{-33,112,-49,123});
    states[112] = new State(new int[]{8,114,7,120,29,-67,2,-67},new int[]{-28,113,-27,119});
    states[113] = new State(-63);
    states[114] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,115,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[115] = new State(new int[]{28,116,39,13,41,15,42,17,40,19,46,21,47,23,48,25,49,27,50,29,51,31,52,33,53,35,43,37,44,39});
    states[116] = new State(-90,new int[]{-33,117,-49,123});
    states[117] = new State(new int[]{8,114,7,120,29,-67,2,-67},new int[]{-28,118,-27,119});
    states[118] = new State(-64);
    states[119] = new State(-65);
    states[120] = new State(new int[]{28,121});
    states[121] = new State(-90,new int[]{-33,122,-49,123});
    states[122] = new State(-66);
    states[123] = new State(new int[]{30,124});
    states[124] = new State(new int[]{45,59,16,69,17,70,18,71,19,72,33,73,24,74,6,109,5,132,3,137,10,145,11,148,12,150,15,152},new int[]{-32,125,-23,160,-21,9,-9,10,-1,103,-8,104,-6,105,-10,60,-7,106,-20,107,-22,108,-24,130,-25,131,-26,136,-16,144,-17,147,-18,149,-19,151});
    states[125] = new State(new int[]{29,126});
    states[126] = new State(new int[]{31,127,45,59,16,69,17,70,18,71,19,72,33,73,24,74,6,109,5,132,3,137,10,145,11,148,12,150,15,152},new int[]{-23,129,-21,9,-9,10,-1,103,-8,104,-6,105,-10,60,-7,106,-20,107,-22,108,-24,130,-25,131,-26,136,-16,144,-17,147,-18,149,-19,151});
    states[127] = new State(-91,new int[]{-50,128});
    states[128] = new State(-89);
    states[129] = new State(-12);
    states[130] = new State(-16);
    states[131] = new State(-17);
    states[132] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,133,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[133] = new State(new int[]{28,134,39,13,41,15,42,17,40,19,46,21,47,23,48,25,49,27,50,29,51,31,52,33,53,35,43,37,44,39});
    states[134] = new State(-90,new int[]{-33,135,-49,123});
    states[135] = new State(-68);
    states[136] = new State(-18);
    states[137] = new State(new int[]{45,59},new int[]{-3,138,-1,143});
    states[138] = new State(new int[]{4,139});
    states[139] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79},new int[]{-5,140,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[140] = new State(new int[]{28,141,39,13,41,15,42,17,40,19,46,21,47,23,48,25,49,27,50,29,51,31,52,33,53,35,43,37,44,39});
    states[141] = new State(-90,new int[]{-33,142,-49,123});
    states[142] = new State(-69);
    states[143] = new State(-70);
    states[144] = new State(-19);
    states[145] = new State(new int[]{40,41,54,43,45,59,16,69,17,70,18,71,19,72,33,73,24,74,20,79,29,-73,2,-73},new int[]{-5,146,-8,45,-6,46,-9,47,-1,58,-10,60,-7,66});
    states[146] = new State(new int[]{39,13,41,15,42,17,40,19,46,21,47,23,48,25,49,27,50,29,51,31,52,33,53,35,43,37,44,39,29,-72,2,-72});
    states[147] = new State(-20);
    states[148] = new State(-74);
    states[149] = new State(-21);
    states[150] = new State(-75);
    states[151] = new State(-22);
    states[152] = new State(new int[]{45,59},new int[]{-40,153,-2,159,-1,158});
    states[153] = new State(new int[]{27,154,29,-23,2,-23});
    states[154] = new State(new int[]{45,59},new int[]{-2,155,-1,158});
    states[155] = new State(new int[]{26,156,27,-28,29,-28,2,-28});
    states[156] = new State(new int[]{45,59},new int[]{-1,157});
    states[157] = new State(-26);
    states[158] = new State(-25);
    states[159] = new State(new int[]{26,156,27,-27,29,-27,2,-27});
    states[160] = new State(-11);
    states[161] = new State(-7);
    states[162] = new State(-8);
    states[163] = new State(new int[]{9,169},new int[]{-41,164});
    states[164] = new State(-93,new int[]{-51,165});
    states[165] = new State(-90,new int[]{-33,166,-49,123});
    states[166] = new State(-94,new int[]{-52,167});
    states[167] = new State(-91,new int[]{-50,168});
    states[168] = new State(-92);
    states[169] = new State(new int[]{45,59},new int[]{-4,170,-1,187});
    states[170] = new State(new int[]{20,171});
    states[171] = new State(new int[]{45,59,21,-105},new int[]{-39,172,-38,179,-37,186,-36,182,-1,185});
    states[172] = new State(new int[]{21,173});
    states[173] = new State(new int[]{28,174,32,175});
    states[174] = new State(-95);
    states[175] = new State(new int[]{45,59},new int[]{-42,176,-43,178,-1,98});
    states[176] = new State(new int[]{28,177});
    states[177] = new State(-96);
    states[178] = new State(-99);
    states[179] = new State(new int[]{27,180,21,-104});
    states[180] = new State(new int[]{45,59},new int[]{-37,181,-36,182,-1,185});
    states[181] = new State(-103);
    states[182] = new State(new int[]{28,183});
    states[183] = new State(new int[]{45,59},new int[]{-42,184,-43,178,-1,98});
    states[184] = new State(-101);
    states[185] = new State(-100);
    states[186] = new State(-102);
    states[187] = new State(-71);
    states[188] = new State(-4);
    states[189] = new State(-9);
    states[190] = new State(new int[]{45,59},new int[]{-1,191});
    states[191] = new State(new int[]{29,192});
    states[192] = new State(-5);

    rules[1] = new Rule(-48, new int[]{-34,2});
    rules[2] = new Rule(-34, new int[]{-44,-30,-46});
    rules[3] = new Rule(-44, new int[]{});
    rules[4] = new Rule(-44, new int[]{-44,-45});
    rules[5] = new Rule(-45, new int[]{13,-1,29});
    rules[6] = new Rule(-29, new int[]{-23});
    rules[7] = new Rule(-29, new int[]{-35});
    rules[8] = new Rule(-35, new int[]{-15});
    rules[9] = new Rule(-30, new int[]{-29});
    rules[10] = new Rule(-30, new int[]{-30,29,-29});
    rules[11] = new Rule(-32, new int[]{-23});
    rules[12] = new Rule(-32, new int[]{-32,29,-23});
    rules[13] = new Rule(-23, new int[]{-21});
    rules[14] = new Rule(-23, new int[]{-20});
    rules[15] = new Rule(-23, new int[]{-22});
    rules[16] = new Rule(-23, new int[]{-24});
    rules[17] = new Rule(-23, new int[]{-25});
    rules[18] = new Rule(-23, new int[]{-26});
    rules[19] = new Rule(-23, new int[]{-16});
    rules[20] = new Rule(-23, new int[]{-17});
    rules[21] = new Rule(-23, new int[]{-18});
    rules[22] = new Rule(-23, new int[]{-19});
    rules[23] = new Rule(-19, new int[]{15,-40});
    rules[24] = new Rule(-1, new int[]{45});
    rules[25] = new Rule(-2, new int[]{-1});
    rules[26] = new Rule(-2, new int[]{-2,26,-1});
    rules[27] = new Rule(-40, new int[]{-2});
    rules[28] = new Rule(-40, new int[]{-40,27,-2});
    rules[29] = new Rule(-20, new int[]{-9,28,-43,34,-5});
    rules[30] = new Rule(-21, new int[]{-9,34,-5});
    rules[31] = new Rule(-21, new int[]{-9,-47,-5});
    rules[32] = new Rule(-47, new int[]{35});
    rules[33] = new Rule(-47, new int[]{36});
    rules[34] = new Rule(-47, new int[]{37});
    rules[35] = new Rule(-47, new int[]{38});
    rules[36] = new Rule(-5, new int[]{-5,39,-5});
    rules[37] = new Rule(-5, new int[]{-5,41,-5});
    rules[38] = new Rule(-5, new int[]{-5,42,-5});
    rules[39] = new Rule(-5, new int[]{-5,40,-5});
    rules[40] = new Rule(-5, new int[]{-5,46,-5});
    rules[41] = new Rule(-5, new int[]{-5,47,-5});
    rules[42] = new Rule(-5, new int[]{-5,48,-5});
    rules[43] = new Rule(-5, new int[]{-5,49,-5});
    rules[44] = new Rule(-5, new int[]{-5,50,-5});
    rules[45] = new Rule(-5, new int[]{-5,51,-5});
    rules[46] = new Rule(-5, new int[]{-5,52,-5});
    rules[47] = new Rule(-5, new int[]{-5,53,-5});
    rules[48] = new Rule(-5, new int[]{-5,43,-5});
    rules[49] = new Rule(-5, new int[]{-5,44,-5});
    rules[50] = new Rule(-5, new int[]{40,-5});
    rules[51] = new Rule(-5, new int[]{54,-5});
    rules[52] = new Rule(-5, new int[]{-8});
    rules[53] = new Rule(-5, new int[]{-7});
    rules[54] = new Rule(-5, new int[]{20,-5,21});
    rules[55] = new Rule(-5, new int[]{-1});
    rules[56] = new Rule(-7, new int[]{16});
    rules[57] = new Rule(-7, new int[]{17});
    rules[58] = new Rule(-7, new int[]{18});
    rules[59] = new Rule(-7, new int[]{19});
    rules[60] = new Rule(-7, new int[]{33});
    rules[61] = new Rule(-31, new int[]{-5});
    rules[62] = new Rule(-31, new int[]{-31,27,-5});
    rules[63] = new Rule(-22, new int[]{6,-5,28,-33,-28});
    rules[64] = new Rule(-28, new int[]{8,-5,28,-33,-28});
    rules[65] = new Rule(-28, new int[]{-27});
    rules[66] = new Rule(-27, new int[]{7,28,-33});
    rules[67] = new Rule(-27, new int[]{});
    rules[68] = new Rule(-25, new int[]{5,-5,28,-33});
    rules[69] = new Rule(-26, new int[]{3,-3,4,-5,28,-33});
    rules[70] = new Rule(-3, new int[]{-1});
    rules[71] = new Rule(-4, new int[]{-1});
    rules[72] = new Rule(-16, new int[]{10,-5});
    rules[73] = new Rule(-16, new int[]{10});
    rules[74] = new Rule(-17, new int[]{11});
    rules[75] = new Rule(-18, new int[]{12});
    rules[76] = new Rule(-24, new int[]{-6});
    rules[77] = new Rule(-9, new int[]{-1});
    rules[78] = new Rule(-9, new int[]{-8});
    rules[79] = new Rule(-8, new int[]{-6});
    rules[80] = new Rule(-8, new int[]{-10,26,-1});
    rules[81] = new Rule(-8, new int[]{-7,26,-1});
    rules[82] = new Rule(-8, new int[]{24,-31,25});
    rules[83] = new Rule(-8, new int[]{-10,24,-5,25});
    rules[84] = new Rule(-8, new int[]{24,-5,3,-1,4,-5,-11,25});
    rules[85] = new Rule(-11, new int[]{});
    rules[86] = new Rule(-11, new int[]{6,-5});
    rules[87] = new Rule(-10, new int[]{-1});
    rules[88] = new Rule(-10, new int[]{-8});
    rules[89] = new Rule(-33, new int[]{-49,30,-32,29,31,-50});
    rules[90] = new Rule(-49, new int[]{});
    rules[91] = new Rule(-50, new int[]{});
    rules[92] = new Rule(-15, new int[]{-49,-41,-51,-33,-52,-50});
    rules[93] = new Rule(-51, new int[]{});
    rules[94] = new Rule(-52, new int[]{});
    rules[95] = new Rule(-41, new int[]{9,-4,20,-39,21,28});
    rules[96] = new Rule(-41, new int[]{9,-4,20,-39,21,32,-42,28});
    rules[97] = new Rule(-6, new int[]{-9,20,-14,21});
    rules[98] = new Rule(-43, new int[]{-1});
    rules[99] = new Rule(-42, new int[]{-43});
    rules[100] = new Rule(-36, new int[]{-1});
    rules[101] = new Rule(-37, new int[]{-36,28,-42});
    rules[102] = new Rule(-38, new int[]{-37});
    rules[103] = new Rule(-38, new int[]{-38,27,-37});
    rules[104] = new Rule(-39, new int[]{-38});
    rules[105] = new Rule(-39, new int[]{});
    rules[106] = new Rule(-12, new int[]{-5});
    rules[107] = new Rule(-12, new int[]{-1,34,-5});
    rules[108] = new Rule(-13, new int[]{-12});
    rules[109] = new Rule(-13, new int[]{-13,27,-12});
    rules[110] = new Rule(-14, new int[]{-13});
    rules[111] = new Rule(-14, new int[]{});
    rules[112] = new Rule(-46, new int[]{29});
    rules[113] = new Rule(-46, new int[]{});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
      case 2: // program -> import_clause, decl_and_stmt_list, optional_semicolon
{
			// main program
			if (!is_unit_to_be_parsed) {
				var ul = ValueStack[ValueStack.Depth-3].stn as uses_list;
				var stl = ValueStack[ValueStack.Depth-2].stn as statement_list;
				stl.left_logical_bracket = new token_info("");
				stl.right_logical_bracket = new token_info("");
				var bl = new block(decl, stl, LocationStack[LocationStack.Depth-2]);
				decl.AddFirst(decl_forward.defs);
				root = CurrentSemanticValue.stn = NewProgramModule(null, null, ul, bl, ValueStack[ValueStack.Depth-1].ob, CurrentLocationSpan);
				root.source_context = bl.source_context;
			}
			// unit
			else {
				decl.AddFirst(decl_forward.defs);
				var interface_part = new interface_node(decl as declarations, ValueStack[ValueStack.Depth-3].stn as uses_list, null, null);
				var initialization_part = new initfinal_part(null, ValueStack[ValueStack.Depth-2].stn as statement_list, null, null, null, CurrentLocationSpan);

				root = CurrentSemanticValue.stn = new unit_module(
					new unit_name(new ident(Path.GetFileNameWithoutExtension(parserTools.CurrentFileName)),
					UnitHeaderKeyword.Unit, CurrentLocationSpan), interface_part, null,
					initialization_part.initialization_sect,
					initialization_part.finalization_sect, null, CurrentLocationSpan);
			}

		}
        break;
      case 3: // import_clause -> /* empty */
{
			CurrentSemanticValue.stn = null;
		}
        break;
      case 4: // import_clause -> import_clause, import_clause_one
{
   			if (parserTools.build_tree_for_formatter)
   			{
	        	if (ValueStack[ValueStack.Depth-2].stn == null)
                {
	        		CurrentSemanticValue.stn = new uses_closure(ValueStack[ValueStack.Depth-1].stn as uses_list,CurrentLocationSpan);
                }
	        	else {
                    (ValueStack[ValueStack.Depth-2].stn as uses_closure).AddUsesList(ValueStack[ValueStack.Depth-1].stn as uses_list,CurrentLocationSpan);
                    CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-2].stn;
                }
   			}
   			else
   			{
	        	if (ValueStack[ValueStack.Depth-2].stn == null)
                {
                    CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn;
                    CurrentSemanticValue.stn.source_context = CurrentLocationSpan;
                }
	        	else
                {
                    (ValueStack[ValueStack.Depth-2].stn as uses_list).AddUsesList(ValueStack[ValueStack.Depth-1].stn as uses_list,CurrentLocationSpan);
                    CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-2].stn;
                    CurrentSemanticValue.stn.source_context = CurrentLocationSpan;
                }
			}
		}
        break;
      case 5: // import_clause_one -> IMPORT, ident, SEMICOLON
{
			CurrentSemanticValue.stn = new uses_list(new unit_or_namespace(new ident_list(ValueStack[ValueStack.Depth-2].id as ident, LocationStack[LocationStack.Depth-2]), LocationStack[LocationStack.Depth-2]),LocationStack[LocationStack.Depth-2]);
			CurrentSemanticValue.stn.source_context = CurrentLocationSpan;
		}
        break;
      case 6: // decl_or_stmt -> stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 7: // decl_or_stmt -> decl
{ CurrentSemanticValue.stn = null; }
        break;
      case 8: // decl -> proc_func_decl
{
			CurrentSemanticValue.stn = null;
			decl.Add(ValueStack[ValueStack.Depth-1].stn as procedure_definition, CurrentLocationSpan);
		}
        break;
      case 9: // decl_and_stmt_list -> decl_or_stmt
{
			if (ValueStack[ValueStack.Depth-1].stn is statement st)
				CurrentSemanticValue.stn = new statement_list(ValueStack[ValueStack.Depth-1].stn as statement, LocationStack[LocationStack.Depth-1]);
			else
				CurrentSemanticValue.stn =  new statement_list();
		}
        break;
      case 10: // decl_and_stmt_list -> decl_and_stmt_list, SEMICOLON, decl_or_stmt
{
			if (ValueStack[ValueStack.Depth-1].stn is statement st)
				CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as statement_list).Add(st, CurrentLocationSpan);
			else
				CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as statement_list);
		}
        break;
      case 11: // stmt_list -> stmt
{
			CurrentSemanticValue.stn = new statement_list(ValueStack[ValueStack.Depth-1].stn as statement, LocationStack[LocationStack.Depth-1]);
		}
        break;
      case 12: // stmt_list -> stmt_list, SEMICOLON, stmt
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as statement_list).Add(ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan);
		}
        break;
      case 13: // stmt -> assign_stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 14: // stmt -> var_stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 15: // stmt -> if_stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 16: // stmt -> proc_func_call_stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 17: // stmt -> while_stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 18: // stmt -> for_stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 19: // stmt -> return_stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 20: // stmt -> break_stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 21: // stmt -> continue_stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 22: // stmt -> global_stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 23: // global_stmt -> GLOBAL, dotted_ident_list
{
			/*foreach (var id in ($2 as ident_list).idents) {
				// имя па�?аме�?�?а совпадае�? с именем глобал�?ной пе�?еменной
				/*if (symbolTable.Contains(id.name)) {
					parserTools.AddErrorFromResource("GLOBAL_VAR_{0}_SIM_PARAMETER", @$, id.name);
					$$ = null;
				}
				// вс�? о�?ли�?но!
				else {
					$$ = new empty_statement();
					$$.source_context = null;
					symbolTable.Add(id.name);
				//}
			}*/
			CurrentSemanticValue.stn = new global_statement(ValueStack[ValueStack.Depth-1].stn as ident_list, CurrentLocationSpan);
		}
        break;
      case 24: // ident -> ID
{
			if (ValueStack[ValueStack.Depth-1].id.name == "result")
				ValueStack[ValueStack.Depth-1].id.name = "%result";

			CurrentSemanticValue.id = ValueStack[ValueStack.Depth-1].id;
		}
        break;
      case 25: // dotted_ident -> ident
{ CurrentSemanticValue.id = ValueStack[ValueStack.Depth-1].id; }
        break;
      case 26: // dotted_ident -> dotted_ident, DOT, ident
{
			CurrentSemanticValue.id = new ident(ValueStack[ValueStack.Depth-3].id.name + "." + ValueStack[ValueStack.Depth-1].id.name);
		}
        break;
      case 27: // dotted_ident_list -> dotted_ident
{
			CurrentSemanticValue.stn = new ident_list(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 28: // dotted_ident_list -> dotted_ident_list, COMMA, dotted_ident
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as ident_list).Add(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 29: // var_stmt -> variable, COLON, simple_type_identifier, ASSIGN, expr
{
			var vds = new var_def_statement(new ident_list(ValueStack[ValueStack.Depth-5].ex as ident, LocationStack[LocationStack.Depth-5]), ValueStack[ValueStack.Depth-3].td, ValueStack[ValueStack.Depth-1].ex, definition_attribute.None, false, CurrentLocationSpan);

			if (ValueStack[ValueStack.Depth-5].ex is ident id && symbolTable.OuterScope == null && !globalVariables.Contains(id.name)) {
					globalVariables.Add(id.name);
					CurrentSemanticValue.stn = new assign(id as addressed_value, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan);
					decl.Add(new variable_definitions(vds, CurrentLocationSpan), CurrentLocationSpan);
			}
			else
				CurrentSemanticValue.stn = new var_statement(vds, CurrentLocationSpan);
		}
        break;
      case 30: // assign_stmt -> variable, ASSIGN, expr
{
			var ass = new assign(ValueStack[ValueStack.Depth-3].ex as addressed_value, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan);

			if (ValueStack[ValueStack.Depth-3].ex is ident id && symbolTable.OuterScope == null && !globalVariables.Contains(id.name)) {
				globalVariables.Add(id.name);
				ass.first_assignment_defines_type = true;
				type_definition ntr = new named_type_reference(new ident("integer"));
				var vds = new var_def_statement(new ident_list(id, LocationStack[LocationStack.Depth-3]), ntr, null, definition_attribute.None, false, CurrentLocationSpan);
				decl.Add(new variable_definitions(vds, CurrentLocationSpan), CurrentLocationSpan);
			}
			
			CurrentSemanticValue.stn = ass;

			/*if ($1 is ident id) {
				// об�?явление
				if (!isInsideFunction && ($2 != null || (!symbolTable.Contains(id.name) && (isInsideFunction || !globalVariables.Contains(id.name))))) {

					// об�?явление глобал�?ной пе�?еменной
					if (symbolTable.OuterScope == null) {
						if (globalVariables.Contains(id.name)) {
							parserTools.AddErrorFromResource("This variable is declared before", @$);
						}
						else {
							var ass = new assign(id as addressed_value, $3, $2.type, @$);
							globalVariables.Add(id.name);

							type_definition ntr;

							if ($2 == null) {
								ntr = new named_type_reference(new ident("integer"));
								// ntr = (new same_type_node($3) as type_definition);
								ass.first_assignment_defines_type = true;
							}
							else ntr = $2 as type_definition;

							var vds = new var_def_statement(new ident_list(id, @1), ntr, null, definition_attribute.None, false, @$);
							decl.Add(new variable_definitions(vds, @$), @$);
							$$ = ass;
						}
					}
					// об�?явление локал�?ной пе�?еменной
					else {
						var vds = new var_def_statement(new ident_list(id, @1), $2, $3, definition_attribute.None, false, @$);
						symbolTable.Add(id.name);
						$$ = new var_statement(vds, @$);
					}
				}
				// п�?исваивание
				else {
					$$ = new assign(id as addressed_value, $3, $2.type, @$);
				}
			}
			else {
				$$ = new assign($1 as addressed_value, $3, $2.type, @$);
			}*/
		}
        break;
      case 31: // assign_stmt -> variable, assign_type, expr
{
			if (!(ValueStack[ValueStack.Depth-3].ex is addressed_value))
        		parserTools.AddErrorFromResource("LEFT_SIDE_CANNOT_BE_ASSIGNED_TO",CurrentLocationSpan);
			CurrentSemanticValue.stn = new assign(ValueStack[ValueStack.Depth-3].ex as addressed_value, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan);
		}
        break;
      case 32: // assign_type -> PLUSEQUAL
{ CurrentSemanticValue.op = ValueStack[ValueStack.Depth-1].op; }
        break;
      case 33: // assign_type -> MINUSEQUAL
{ CurrentSemanticValue.op = ValueStack[ValueStack.Depth-1].op; }
        break;
      case 34: // assign_type -> STAREQUAL
{ CurrentSemanticValue.op = ValueStack[ValueStack.Depth-1].op; }
        break;
      case 35: // assign_type -> DIVEQUAL
{ CurrentSemanticValue.op = ValueStack[ValueStack.Depth-1].op; }
        break;
      case 36: // expr -> expr, PLUS, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 37: // expr -> expr, STAR, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 38: // expr -> expr, DIVIDE, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 39: // expr -> expr, MINUS, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 40: // expr -> expr, LESS, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 41: // expr -> expr, GREATER, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 42: // expr -> expr, LESSEQUAL, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 43: // expr -> expr, GREATEREQUAL, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 44: // expr -> expr, EQUAL, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 45: // expr -> expr, NOTEQUAL, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 46: // expr -> expr, AND, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 47: // expr -> expr, OR, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 48: // expr -> expr, SLASHSLASH, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 49: // expr -> expr, PERCENTAGE, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 50: // expr -> MINUS, expr
{ CurrentSemanticValue.ex = new un_expr(ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 51: // expr -> NOT, expr
{ CurrentSemanticValue.ex = new un_expr(ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 52: // expr -> complex_variable
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 53: // expr -> const_value
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 54: // expr -> LPAR, expr, RPAR
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-2].ex; }
        break;
      case 55: // expr -> ident
{
			// �?�?ове�?ка на �?о �?�?о п�?�?аемся с�?и�?а�?�? не ини�?иализи�?ованн�?�? пе�?еменн�?�?
			//if (!symbolTable.Contains($1.name) && !globalVariables.Contains($1.name))
					//parserTools.AddErrorFromResource("USING_VARIABLE_{0}_BEFORE_ASSIGNMENT", @$, $1.name);

			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].id;
		}
        break;
      case 56: // const_value -> INTNUM
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 57: // const_value -> REALNUM
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 58: // const_value -> TRUE
{ CurrentSemanticValue.ex = new ident("true"); }
        break;
      case 59: // const_value -> FALSE
{ CurrentSemanticValue.ex = new ident("false"); }
        break;
      case 60: // const_value -> STRINGNUM
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].stn as literal; }
        break;
      case 61: // expr_list -> expr
{
			CurrentSemanticValue.stn = new expression_list(ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 62: // expr_list -> expr_list, COMMA, expr
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as expression_list).Add(ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 63: // if_stmt -> IF, expr, COLON, block, optional_elif
{
			CurrentSemanticValue.stn = new if_node(ValueStack[ValueStack.Depth-4].ex, ValueStack[ValueStack.Depth-2].stn as statement, ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan);
		}
        break;
      case 64: // optional_elif -> ELIF, expr, COLON, block, optional_elif
{
			CurrentSemanticValue.stn = new if_node(ValueStack[ValueStack.Depth-4].ex, ValueStack[ValueStack.Depth-2].stn as statement, ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan);
		}
        break;
      case 65: // optional_elif -> optional_else
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 66: // optional_else -> ELSE, COLON, block
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 67: // optional_else -> /* empty */
{ CurrentSemanticValue.stn = null; }
        break;
      case 68: // while_stmt -> WHILE, expr, COLON, block
{
			CurrentSemanticValue.stn = new while_node(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].stn as statement, WhileCycleType.While, CurrentLocationSpan);
		}
        break;
      case 69: // for_stmt -> FOR, range_ident, IN, expr, COLON, block
{
			CurrentSemanticValue.stn = new foreach_stmt(ValueStack[ValueStack.Depth-5].id, new no_type_foreach(), ValueStack[ValueStack.Depth-3].ex, (statement)ValueStack[ValueStack.Depth-1].stn, null, CurrentLocationSpan);
		}
        break;
      case 70: // range_ident -> ident
{
			symbolTable.Add(ValueStack[ValueStack.Depth-1].id.name);
			CurrentSemanticValue.id = ValueStack[ValueStack.Depth-1].id;
		}
        break;
      case 71: // func_name_ident -> ident
{
			globalVariables.Add(ValueStack[ValueStack.Depth-1].id.name);
			CurrentSemanticValue.id = ValueStack[ValueStack.Depth-1].id;
		}
        break;
      case 72: // return_stmt -> RETURN, expr
{
			statement res_assign = new assign(new ident("result"), ValueStack[ValueStack.Depth-1].ex, Operators.Assignment, CurrentLocationSpan);
			statement exit_call = new procedure_call(new ident("exit"), true, CurrentLocationSpan);
			CurrentSemanticValue.stn = new statement_list(res_assign, CurrentLocationSpan);
			(CurrentSemanticValue.stn  as statement_list).Add(exit_call, CurrentLocationSpan);
		}
        break;
      case 73: // return_stmt -> RETURN
{
			CurrentSemanticValue.stn = new procedure_call(new ident("exit"), true, CurrentLocationSpan);
		}
        break;
      case 74: // break_stmt -> BREAK
{
			CurrentSemanticValue.stn = new procedure_call(new ident("break"), true, CurrentLocationSpan);
		}
        break;
      case 75: // continue_stmt -> CONTINUE
{
			CurrentSemanticValue.stn = new procedure_call(new ident("continue"), true, CurrentLocationSpan);
		}
        break;
      case 76: // proc_func_call_stmt -> proc_func_call
{
			CurrentSemanticValue.stn = new procedure_call(ValueStack[ValueStack.Depth-1].ex as addressed_value, ValueStack[ValueStack.Depth-1].ex is ident, CurrentLocationSpan);
		}
        break;
      case 77: // variable -> ident
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].id; }
        break;
      case 78: // variable -> complex_variable
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 79: // complex_variable -> proc_func_call
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 80: // complex_variable -> complex_variable_or_ident, DOT, ident
{ CurrentSemanticValue.ex = new dot_node(ValueStack[ValueStack.Depth-3].ex as addressed_value, ValueStack[ValueStack.Depth-1].id as addressed_value, CurrentLocationSpan); }
        break;
      case 81: // complex_variable -> const_value, DOT, ident
{ CurrentSemanticValue.ex = new dot_node(ValueStack[ValueStack.Depth-3].ex as addressed_value, ValueStack[ValueStack.Depth-1].id as addressed_value, CurrentLocationSpan); }
        break;
      case 82: // complex_variable -> LBRACKET, expr_list, RBRACKET
{

			var acn = new array_const_new(ValueStack[ValueStack.Depth-2].stn as expression_list, CurrentLocationSpan);
			var dn = new dot_node(acn as addressed_value, (new ident("ToList")) as addressed_value, CurrentLocationSpan);
			CurrentSemanticValue.ex = new method_call(dn as addressed_value, null, CurrentLocationSpan);
		}
        break;
      case 83: // complex_variable -> complex_variable_or_ident, LBRACKET, expr, RBRACKET
{
			var el = new expression_list(ValueStack[ValueStack.Depth-2].ex as expression);
			CurrentSemanticValue.ex = new indexer(ValueStack[ValueStack.Depth-4].ex as addressed_value, el, CurrentLocationSpan);
		}
        break;
      case 84: // complex_variable -> LBRACKET, expr, FOR, ident, IN, expr, optional_condition, 
               //                     RBRACKET
{
			dot_node dn;
			ident_list idList;
			formal_parameters formalPars;
			statement_list sl;
			function_lambda_definition lambda;
			method_call mc;

			// [ expr1 for ident in expr2 if expr3 ] -> expr2.Where(ident -> expr3).Select(ident -> expr1).ToList()
			if (ValueStack[ValueStack.Depth-2].ex != null) {
				string ident_name = ValueStack[ValueStack.Depth-5].id.name;
				idList = new ident_list(new ident(ident_name), LocationStack[LocationStack.Depth-5]);
				formalPars = new formal_parameters(new typed_parameters(idList, new lambda_inferred_type(new lambda_any_type_node_syntax(), LocationStack[LocationStack.Depth-5]), parametr_kind.none, null, LocationStack[LocationStack.Depth-5]), LocationStack[LocationStack.Depth-5]);

				dn = new dot_node(ValueStack[ValueStack.Depth-3].ex as addressed_value, (new ident("Where")) as addressed_value, CurrentLocationSpan);

				sl = new statement_list(new assign("result",ValueStack[ValueStack.Depth-2].ex,LocationStack[LocationStack.Depth-1]),LocationStack[LocationStack.Depth-1]);
				sl.expr_lambda_body = true;
				lambda = new function_lambda_definition(
				lambdaHelper.CreateLambdaName(), formalPars,
				new lambda_inferred_type(new lambda_any_type_node_syntax(), LocationStack[LocationStack.Depth-5]), sl, CurrentLocationSpan);

				mc = new method_call(dn as addressed_value, new expression_list(lambda as expression), CurrentLocationSpan);
				dn = new dot_node(mc as addressed_value, (new ident("Select")) as addressed_value, CurrentLocationSpan);
			}
			// [ expr1 for ident in expr2 ] -> expr2.Select(ident -> expr1).ToList()
			else
				dn = new dot_node(ValueStack[ValueStack.Depth-3].ex as addressed_value, (new ident("Select")) as addressed_value, CurrentLocationSpan);


			idList = new ident_list(ValueStack[ValueStack.Depth-5].id, LocationStack[LocationStack.Depth-5]);
			formalPars = new formal_parameters(new typed_parameters(idList, new lambda_inferred_type(new lambda_any_type_node_syntax(), LocationStack[LocationStack.Depth-5]), parametr_kind.none, null, LocationStack[LocationStack.Depth-5]), LocationStack[LocationStack.Depth-5]);

			sl = new statement_list(new assign("result",ValueStack[ValueStack.Depth-7].ex,LocationStack[LocationStack.Depth-7]),LocationStack[LocationStack.Depth-7]);
			sl.expr_lambda_body = true;

			lambda = new function_lambda_definition(
				lambdaHelper.CreateLambdaName(), formalPars,
				new lambda_inferred_type(new lambda_any_type_node_syntax(), LocationStack[LocationStack.Depth-5]), sl, CurrentLocationSpan);


			mc = new method_call(dn as addressed_value, new expression_list(lambda as expression), CurrentLocationSpan);
			dn = new dot_node(mc as addressed_value, (new ident("ToList")) as addressed_value, CurrentLocationSpan);
			CurrentSemanticValue.ex = new method_call(dn as addressed_value, null, CurrentLocationSpan);
		}
        break;
      case 85: // optional_condition -> /* empty */
{ CurrentSemanticValue.ex = null; }
        break;
      case 86: // optional_condition -> IF, expr
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 87: // complex_variable_or_ident -> ident
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].id; }
        break;
      case 88: // complex_variable_or_ident -> complex_variable
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 89: // block -> NestedSymbolTableBegin, INDENT, stmt_list, SEMICOLON, UNINDENT, 
               //          NestedSymbolTableEnd
{
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-4].stn as statement_list;
			(CurrentSemanticValue.stn as statement_list).left_logical_bracket = ValueStack[ValueStack.Depth-5].ti;
			(CurrentSemanticValue.stn as statement_list).right_logical_bracket = ValueStack[ValueStack.Depth-3].ti;
			CurrentSemanticValue.stn.source_context = LexLocation.MergeAll(LocationStack[LocationStack.Depth-5],LocationStack[LocationStack.Depth-4],LocationStack[LocationStack.Depth-3]);
		}
        break;
      case 90: // NestedSymbolTableBegin -> /* empty */
{
			symbolTable = new SymbolTable(symbolTable);
		}
        break;
      case 91: // NestedSymbolTableEnd -> /* empty */
{
			symbolTable = symbolTable.OuterScope;
		}
        break;
      case 92: // proc_func_decl -> NestedSymbolTableBegin, proc_func_header, InsideFunction, 
               //                   block, OutsideFunction, NestedSymbolTableEnd
{
			//var pd1 = new procedure_definition($1 as procedure_header, new block(null, $2 as statement_list, @2), @$);
			//pd1.AssignAttrList(null);
			//$$ = pd1;
			CurrentSemanticValue.stn = new procedure_definition(ValueStack[ValueStack.Depth-5].td as procedure_header, new block(null, ValueStack[ValueStack.Depth-3].stn as statement_list, LocationStack[LocationStack.Depth-3]), CurrentLocationSpan);

			var pd = new procedure_definition(ValueStack[ValueStack.Depth-5].td as procedure_header, null, LocationStack[LocationStack.Depth-5]);
            pd.proc_header.proc_attributes.Add(new procedure_attribute(proc_attribute.attr_forward));
			decl_forward.Add(pd, LocationStack[LocationStack.Depth-5]);
		}
        break;
      case 93: // InsideFunction -> /* empty */
{
			isInsideFunction = true;
		}
        break;
      case 94: // OutsideFunction -> /* empty */
{
			isInsideFunction = false;
		}
        break;
      case 95: // proc_func_header -> DEF, func_name_ident, LPAR, optional_form_param_list, RPAR, 
               //                     COLON
{
			CurrentSemanticValue.td = new procedure_header(ValueStack[ValueStack.Depth-3].stn as formal_parameters, new procedure_attributes_list(new List<procedure_attribute>(), CurrentLocationSpan), new method_name(null,null, ValueStack[ValueStack.Depth-5].id, null, CurrentLocationSpan), null, CurrentLocationSpan);
		}
        break;
      case 96: // proc_func_header -> DEF, func_name_ident, LPAR, optional_form_param_list, RPAR, 
               //                     ARROW, form_param_type, COLON
{
			CurrentSemanticValue.td = new function_header(ValueStack[ValueStack.Depth-5].stn as formal_parameters, new procedure_attributes_list(new List<procedure_attribute>(), CurrentLocationSpan), new method_name(null,null, ValueStack[ValueStack.Depth-7].id, null, CurrentLocationSpan), null, ValueStack[ValueStack.Depth-2].td as type_definition, CurrentLocationSpan);
		}
        break;
      case 97: // proc_func_call -> variable, LPAR, optional_act_param_list, RPAR
{
			if (ValueStack[ValueStack.Depth-2].stn is expression_list exprl) {
				expression_list args = new expression_list();
				expression_list kvargs = new expression_list();

				foreach (var expr in exprl.expressions) {
					if (expr is name_assign_expr) {
						kvargs.Add(expr);
						kvargs.source_context = new SourceContext(kvargs.source_context, expr.source_context);
					}
					else if (kvargs.expressions.Count() == 0) {
						args.Add(expr);
						args.source_context = new SourceContext(args.source_context, expr.source_context);
					}
					else parserTools.AddErrorFromResource("Arg after Kvarg", CurrentLocationSpan);
				}

				if (kvargs.expressions.Count() == 0)
					CurrentSemanticValue.ex = new method_call(ValueStack[ValueStack.Depth-4].ex as addressed_value, args, CurrentLocationSpan);
				else {
					method_call mc = new method_call(new ident("!" + (ValueStack[ValueStack.Depth-4].ex as ident).name + ".Get"), kvargs, CurrentLocationSpan);
					dot_node dn = new dot_node(mc as addressed_value, ValueStack[ValueStack.Depth-4].ex as addressed_value, CurrentLocationSpan);
					CurrentSemanticValue.ex = new method_call(dn as addressed_value, args, CurrentLocationSpan);
				}
			}
			else
				CurrentSemanticValue.ex = new method_call(ValueStack[ValueStack.Depth-4].ex as addressed_value, null, CurrentLocationSpan);
		}
        break;
      case 98: // simple_type_identifier -> ident
{
			switch (ValueStack[ValueStack.Depth-1].id.name) {
				case "bool":
					CurrentSemanticValue.td = new named_type_reference("boolean", CurrentLocationSpan);
					break;
				case "int":
					CurrentSemanticValue.td = new named_type_reference("integer", CurrentLocationSpan);
					break;
				case "float":
					CurrentSemanticValue.td = new named_type_reference("real", CurrentLocationSpan);
					break;
				case "str":
					CurrentSemanticValue.td = new named_type_reference("string", CurrentLocationSpan);
					break;

				case "integer":
				case "real":
				case "string":
				case "boolean":
					CurrentSemanticValue.td = new named_type_reference("error", CurrentLocationSpan);
					break;

				default:
					CurrentSemanticValue.td = new named_type_reference(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
					break;
			}
		}
        break;
      case 99: // form_param_type -> simple_type_identifier
{
			CurrentSemanticValue.td = ValueStack[ValueStack.Depth-1].td as named_type_reference;
		}
        break;
      case 100: // param_name -> ident
{
			symbolTable.Add(ValueStack[ValueStack.Depth-1].id.name);
			CurrentSemanticValue.stn = new ident_list(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 101: // form_param_sect -> param_name, COLON, form_param_type
{
			CurrentSemanticValue.stn = new typed_parameters(ValueStack[ValueStack.Depth-3].stn as ident_list, ValueStack[ValueStack.Depth-1].td, parametr_kind.none, null, CurrentLocationSpan);
		}
        break;
      case 102: // form_param_list -> form_param_sect
{
			CurrentSemanticValue.stn = new formal_parameters(ValueStack[ValueStack.Depth-1].stn as typed_parameters, CurrentLocationSpan);
        }
        break;
      case 103: // form_param_list -> form_param_list, COMMA, form_param_sect
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as formal_parameters).Add(ValueStack[ValueStack.Depth-1].stn as typed_parameters, CurrentLocationSpan);
        }
        break;
      case 104: // optional_form_param_list -> form_param_list
{
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn;
			if (CurrentSemanticValue.stn != null)
				CurrentSemanticValue.stn.source_context = CurrentLocationSpan;
		}
        break;
      case 105: // optional_form_param_list -> /* empty */
{
			CurrentSemanticValue.stn = null;
		}
        break;
      case 106: // act_param -> expr
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 107: // act_param -> ident, ASSIGN, expr
{ CurrentSemanticValue.ex = new name_assign_expr(ValueStack[ValueStack.Depth-3].id,ValueStack[ValueStack.Depth-1].ex,CurrentLocationSpan); }
        break;
      case 108: // act_param_list -> act_param
{
			CurrentSemanticValue.stn = new expression_list(ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 109: // act_param_list -> act_param_list, COMMA, act_param
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as expression_list).Add(ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 110: // optional_act_param_list -> act_param_list
{
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn;
			if (CurrentSemanticValue.stn != null)
				CurrentSemanticValue.stn.source_context = CurrentLocationSpan;
		}
        break;
      case 111: // optional_act_param_list -> /* empty */
{
			CurrentSemanticValue.stn = null;
		}
        break;
      case 112: // optional_semicolon -> SEMICOLON
{ CurrentSemanticValue.ob = ValueStack[ValueStack.Depth-1].ti; }
        break;
      case 113: // optional_semicolon -> /* empty */
{ CurrentSemanticValue.ob = null; }
        break;
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }


        public program_module NewProgramModule(program_name progName, Object optHeadCompDirs, uses_list mainUsesClose, syntax_tree_node progBlock, Object optPoint, LexLocation loc)
        {
            var progModule = new program_module(progName, mainUsesClose, progBlock as block, null, loc);
            progModule.Language = "Spython";
            if (optPoint == null && progBlock != null)
            {
                var fp = progBlock.source_context.end_position;
                var err_stn = progBlock;
			    if ((progBlock is block) && (progBlock as block).program_code != null && (progBlock as block).program_code.subnodes != null && (progBlock as block).program_code.subnodes.Count > 0)
                    err_stn = (progBlock as block).program_code.subnodes[(progBlock as block).program_code.subnodes.Count - 1];
                //parserTools.errors.Add(new SPythonUnexpectedToken(parserTools.CurrentFileName, StringResources.Get("TKPOINT"), new SourceContext(fp.line_num, fp.column_num + 1, fp.line_num, fp.column_num + 1, 0, 0), err_stn));
            }
            return progModule;
        }
}
}
