// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.3.6
// Machine:  MACBOOK-PRO-16
// DateTime: 4/25/2025 1:00:06 PM
// UserName: controldata
// Input file <SLangParser.y>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using PascalABCCompiler.SyntaxTree;
using PascalABCCompiler.ParserTools;
using PascalABCCompiler.Errors;
using System.Linq;
using System.Collections.Generic;
using System.IO;
using SLangParser;

namespace SLangParserYacc
{
public enum Tokens {
    error=1,EOF=2,FOR=3,IN=4,WHILE=5,IF=6,
    ELSE=7,ELIF=8,DEF=9,RETURN=10,BREAK=11,CONTINUE=12,
    IMPORT=13,FROM=14,GLOBAL=15,AS=16,PASS=17,CLASS=18,
    LAMBDA=19,INDENT=20,UNINDENT=21,END_OF_FILE=22,END_OF_LINE=23,TASK=24,
    INPUT=25,CHECK=26,TESTS=27,OUTPUT=28,INTNUM=29,REALNUM=30,
    TRUE=31,FALSE=32,LPAR=33,RPAR=34,LBRACE=35,RBRACE=36,
    LBRACKET=37,RBRACKET=38,DOT=39,COMMA=40,COLON=41,SEMICOLON=42,
    ARROW=43,STRINGNUM=44,ASSIGN=45,PLUSEQUAL=46,MINUSEQUAL=47,STAREQUAL=48,
    DIVEQUAL=49,PLUS=50,MINUS=51,STAR=52,DIVIDE=53,SLASHSLASH=54,
    PERCENTAGE=55,ID=56,LESS=57,GREATER=58,LESSEQUAL=59,GREATEREQUAL=60,
    EQUAL=61,NOTEQUAL=62,AND=63,OR=64,NOT=65,STARSTAR=66};

public partial struct ValueType
{
	public expression ex;
	public ident id;
    public Object ob;
    public op_type_node op;
    public syntax_tree_node stn;
    public token_info ti;
    public type_definition td;
}
// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

public partial class SLangGPPGParser: ShiftReduceParser<ValueType, LexLocation>
{
  // Verbatim content from SLangParser.y
   	public syntax_tree_node root;
	public List<Error> errors;
	public SLangParserTools parserTools;
	public List<compiler_directive> CompilerDirectives;
	public ParserLambdaHelper lambdaHelper = new ParserLambdaHelper();
	public bool is_unit_to_be_parsed = false;

	public SLangGPPGParser(AbstractScanner<ValueType, LexLocation> scanner, SLangParserTools parserTools,
	bool isUnitToBeParsed) : base(scanner) 
	{ 
		this.parserTools = parserTools;
		this.is_unit_to_be_parsed = isUnitToBeParsed;
	}
  // End verbatim content from SLangParser.y

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[133];
  private static State[] states = new State[208];
  private static string[] nonTerms = new string[] {
      "ident", "dotted_ident", "func_name_ident", "task_id", "expr", "proc_func_call", 
      "const_value", "variable", "optional_condition", "act_param", "act_param_list", 
      "optional_act_param_list", "proc_func_decl", "return_stmt", "break_stmt", 
      "continue_stmt", "global_stmt", "pass_stmt", "var_stmt", "assign_stmt", 
      "if_stmt", "stmt", "proc_func_call_stmt", "while_stmt", "for_stmt", "optional_else", 
      "optional_elif", "expr_list", "stmt_list", "block", "program", "param_name", 
      "form_param_sect", "form_param_list", "optional_form_param_list", "dotted_ident_list", 
      "ident_as_ident", "ident_as_ident_list", "proc_func_header", "type_ref", 
      "simple_type_identifier", "template_type", "import_clause", "template_type_params", 
      "template_param_list", "optional_semicolon", "end_of_line", "assign_type", 
      "task_definition", "input_section", "check_section", "tests_section", "output_section", 
      "$accept", };

  static SLangGPPGParser() {
    states[0] = new State(new int[]{56,62,29,67,30,68,31,69,32,70,44,71,37,72,6,121,5,141,3,146,25,153,26,157,27,161,28,165,10,169,11,172,12,174,15,176,17,185,24,186,13,191,14,199,42,-5,23,-5,22,-5},new int[]{-31,1,-29,3,-22,206,-20,8,-8,9,-1,61,-6,117,-7,118,-19,119,-21,120,-23,139,-24,140,-25,145,-50,152,-51,156,-52,160,-53,164,-14,168,-15,171,-16,173,-17,175,-18,184,-43,190});
    states[1] = new State(new int[]{2,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{42,207,23,204,22,-132},new int[]{-46,4,-47,6});
    states[4] = new State(new int[]{22,5});
    states[5] = new State(-2);
    states[6] = new State(new int[]{56,62,29,67,30,68,31,69,32,70,44,71,37,72,6,121,5,141,3,146,25,153,26,157,27,161,28,165,10,169,11,172,12,174,15,176,17,185,24,186,13,191,14,199,42,-5,23,-5,22,-5},new int[]{-22,7,-20,8,-8,9,-1,61,-6,117,-7,118,-19,119,-21,120,-23,139,-24,140,-25,145,-50,152,-51,156,-52,160,-53,164,-14,168,-15,171,-16,173,-17,175,-18,184,-43,190});
    states[7] = new State(-13);
    states[8] = new State(-14);
    states[9] = new State(new int[]{45,10,33,51,39,90,37,92,41,97,46,113,47,114,48,115,49,116},new int[]{-48,95});
    states[10] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,11,-8,50,-1,61,-6,63,-7,64});
    states[11] = new State(new int[]{6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,38,54,40,55,42,66,44,42,-48,23,-48,22,-48});
    states[12] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,13,-8,50,-1,61,-6,63,-7,64});
    states[13] = new State(new int[]{7,14,6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,38,54,40,55,42,66,44});
    states[14] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,15,-8,50,-1,61,-6,63,-7,64});
    states[15] = new State(new int[]{6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,38,54,40,55,42,66,44,42,-54,23,-54,22,-54,7,-54,40,-54,34,-54,3,-54,38,-54,41,-54});
    states[16] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,17,-8,50,-1,61,-6,63,-7,64});
    states[17] = new State(new int[]{6,12,50,-55,52,18,53,20,51,-55,57,-55,58,-55,59,-55,60,-55,61,-55,62,-55,63,-55,64,-55,54,40,55,42,66,44,42,-55,23,-55,22,-55,7,-55,40,-55,34,-55,3,-55,38,-55,41,-55});
    states[18] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,19,-8,50,-1,61,-6,63,-7,64});
    states[19] = new State(new int[]{6,12,50,-56,52,-56,53,-56,51,-56,57,-56,58,-56,59,-56,60,-56,61,-56,62,-56,63,-56,64,-56,54,-56,55,-56,66,44,42,-56,23,-56,22,-56,7,-56,40,-56,34,-56,3,-56,38,-56,41,-56});
    states[20] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,21,-8,50,-1,61,-6,63,-7,64});
    states[21] = new State(new int[]{6,12,50,-57,52,-57,53,-57,51,-57,57,-57,58,-57,59,-57,60,-57,61,-57,62,-57,63,-57,64,-57,54,-57,55,-57,66,44,42,-57,23,-57,22,-57,7,-57,40,-57,34,-57,3,-57,38,-57,41,-57});
    states[22] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,23,-8,50,-1,61,-6,63,-7,64});
    states[23] = new State(new int[]{6,12,50,-58,52,18,53,20,51,-58,57,-58,58,-58,59,-58,60,-58,61,-58,62,-58,63,-58,64,-58,54,40,55,42,66,44,42,-58,23,-58,22,-58,7,-58,40,-58,34,-58,3,-58,38,-58,41,-58});
    states[24] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,25,-8,50,-1,61,-6,63,-7,64});
    states[25] = new State(new int[]{6,12,50,16,52,18,53,20,51,22,57,-59,58,-59,59,-59,60,-59,61,-59,62,-59,63,-59,64,-59,54,40,55,42,66,44,42,-59,23,-59,22,-59,7,-59,40,-59,34,-59,3,-59,38,-59,41,-59});
    states[26] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,27,-8,50,-1,61,-6,63,-7,64});
    states[27] = new State(new int[]{6,12,50,16,52,18,53,20,51,22,57,-60,58,-60,59,-60,60,-60,61,-60,62,-60,63,-60,64,-60,54,40,55,42,66,44,42,-60,23,-60,22,-60,7,-60,40,-60,34,-60,3,-60,38,-60,41,-60});
    states[28] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,29,-8,50,-1,61,-6,63,-7,64});
    states[29] = new State(new int[]{6,12,50,16,52,18,53,20,51,22,57,-61,58,-61,59,-61,60,-61,61,-61,62,-61,63,-61,64,-61,54,40,55,42,66,44,42,-61,23,-61,22,-61,7,-61,40,-61,34,-61,3,-61,38,-61,41,-61});
    states[30] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,31,-8,50,-1,61,-6,63,-7,64});
    states[31] = new State(new int[]{6,12,50,16,52,18,53,20,51,22,57,-62,58,-62,59,-62,60,-62,61,-62,62,-62,63,-62,64,-62,54,40,55,42,66,44,42,-62,23,-62,22,-62,7,-62,40,-62,34,-62,3,-62,38,-62,41,-62});
    states[32] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,33,-8,50,-1,61,-6,63,-7,64});
    states[33] = new State(new int[]{6,12,50,16,52,18,53,20,51,22,57,-63,58,-63,59,-63,60,-63,61,-63,62,-63,63,-63,64,-63,54,40,55,42,66,44,42,-63,23,-63,22,-63,7,-63,40,-63,34,-63,3,-63,38,-63,41,-63});
    states[34] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,35,-8,50,-1,61,-6,63,-7,64});
    states[35] = new State(new int[]{6,12,50,16,52,18,53,20,51,22,57,-64,58,-64,59,-64,60,-64,61,-64,62,-64,63,-64,64,-64,54,40,55,42,66,44,42,-64,23,-64,22,-64,7,-64,40,-64,34,-64,3,-64,38,-64,41,-64});
    states[36] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,37,-8,50,-1,61,-6,63,-7,64});
    states[37] = new State(new int[]{6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,-65,64,-65,54,40,55,42,66,44,42,-65,23,-65,22,-65,7,-65,40,-65,34,-65,3,-65,38,-65,41,-65});
    states[38] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,39,-8,50,-1,61,-6,63,-7,64});
    states[39] = new State(new int[]{6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,-66,54,40,55,42,66,44,42,-66,23,-66,22,-66,7,-66,40,-66,34,-66,3,-66,38,-66,41,-66});
    states[40] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,41,-8,50,-1,61,-6,63,-7,64});
    states[41] = new State(new int[]{6,12,50,-67,52,-67,53,-67,51,-67,57,-67,58,-67,59,-67,60,-67,61,-67,62,-67,63,-67,64,-67,54,-67,55,-67,66,44,42,-67,23,-67,22,-67,7,-67,40,-67,34,-67,3,-67,38,-67,41,-67});
    states[42] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,43,-8,50,-1,61,-6,63,-7,64});
    states[43] = new State(new int[]{6,12,50,-68,52,-68,53,-68,51,-68,57,-68,58,-68,59,-68,60,-68,61,-68,62,-68,63,-68,64,-68,54,-68,55,-68,66,44,42,-68,23,-68,22,-68,7,-68,40,-68,34,-68,3,-68,38,-68,41,-68});
    states[44] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,45,-8,50,-1,61,-6,63,-7,64});
    states[45] = new State(new int[]{6,12,50,-69,52,-69,53,-69,51,-69,57,-69,58,-69,59,-69,60,-69,61,-69,62,-69,63,-69,64,-69,54,-69,55,-69,66,44,42,-69,23,-69,22,-69,7,-69,40,-69,34,-69,3,-69,38,-69,41,-69});
    states[46] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,47,-8,50,-1,61,-6,63,-7,64});
    states[47] = new State(new int[]{6,12,50,-70,52,18,53,20,51,-70,57,-70,58,-70,59,-70,60,-70,61,-70,62,-70,63,-70,64,-70,54,40,55,42,66,44,42,-70,23,-70,22,-70,7,-70,40,-70,34,-70,3,-70,38,-70,41,-70});
    states[48] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,49,-8,50,-1,61,-6,63,-7,64});
    states[49] = new State(new int[]{6,12,50,-71,52,-71,53,-71,51,-71,57,-71,58,-71,59,-71,60,-71,61,-71,62,-71,63,-71,64,-71,54,-71,55,-71,66,44,42,-71,23,-71,22,-71,7,-71,40,-71,34,-71,3,-71,38,-71,41,-71});
    states[50] = new State(new int[]{33,51,39,90,37,92,6,-72,50,-72,52,-72,53,-72,51,-72,57,-72,58,-72,59,-72,60,-72,61,-72,62,-72,63,-72,64,-72,54,-72,55,-72,66,-72,42,-72,23,-72,22,-72,7,-72,40,-72,34,-72,3,-72,38,-72,41,-72});
    states[51] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77,34,-128},new int[]{-12,52,-11,54,-10,89,-5,57,-8,50,-1,58,-6,63,-7,64});
    states[52] = new State(new int[]{34,53});
    states[53] = new State(-108);
    states[54] = new State(new int[]{40,55,34,-127});
    states[55] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-10,56,-5,57,-8,50,-1,58,-6,63,-7,64});
    states[56] = new State(-126);
    states[57] = new State(new int[]{6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,38,54,40,55,42,66,44,40,-123,34,-123});
    states[58] = new State(new int[]{45,59,33,-95,39,-95,37,-95,6,-95,50,-95,52,-95,53,-95,51,-95,57,-95,58,-95,59,-95,60,-95,61,-95,62,-95,63,-95,64,-95,54,-95,55,-95,66,-95,40,-95,34,-95});
    states[59] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,60,-8,50,-1,61,-6,63,-7,64});
    states[60] = new State(new int[]{6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,38,54,40,55,42,66,44,40,-124,34,-124});
    states[61] = new State(-95);
    states[62] = new State(-37);
    states[63] = new State(-96);
    states[64] = new State(new int[]{39,65,6,-73,50,-73,52,-73,53,-73,51,-73,57,-73,58,-73,59,-73,60,-73,61,-73,62,-73,63,-73,64,-73,54,-73,55,-73,66,-73,42,-73,23,-73,22,-73,7,-73,40,-73,34,-73,3,-73,38,-73,41,-73});
    states[65] = new State(new int[]{56,62},new int[]{-1,66});
    states[66] = new State(-98);
    states[67] = new State(-75);
    states[68] = new State(-76);
    states[69] = new State(-77);
    states[70] = new State(-78);
    states[71] = new State(-79);
    states[72] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-28,73,-5,80,-8,50,-1,61,-6,63,-7,64});
    states[73] = new State(new int[]{38,74,40,75});
    states[74] = new State(-99);
    states[75] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,76,-8,50,-1,61,-6,63,-7,64});
    states[76] = new State(new int[]{6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,38,54,40,55,42,66,44,38,-81,40,-81});
    states[77] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,78,-8,50,-1,61,-6,63,-7,64});
    states[78] = new State(new int[]{34,79,6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,38,54,40,55,42,66,44});
    states[79] = new State(-74);
    states[80] = new State(new int[]{3,81,6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,38,54,40,55,42,66,44,38,-80,40,-80});
    states[81] = new State(new int[]{56,62},new int[]{-1,82});
    states[82] = new State(new int[]{4,83});
    states[83] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,84,-8,50,-1,61,-6,63,-7,64});
    states[84] = new State(new int[]{6,87,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,38,54,40,55,42,66,44,38,-102},new int[]{-9,85});
    states[85] = new State(new int[]{38,86});
    states[86] = new State(-101);
    states[87] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,88,-8,50,-1,61,-6,63,-7,64});
    states[88] = new State(new int[]{7,14,6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,38,54,40,55,42,66,44,38,-103});
    states[89] = new State(-125);
    states[90] = new State(new int[]{56,62},new int[]{-1,91});
    states[91] = new State(-97);
    states[92] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,93,-8,50,-1,61,-6,63,-7,64});
    states[93] = new State(new int[]{38,94,6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,38,54,40,55,42,66,44});
    states[94] = new State(-100);
    states[95] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,96,-8,50,-1,61,-6,63,-7,64});
    states[96] = new State(new int[]{6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,38,54,40,55,42,66,44,42,-49,23,-49,22,-49});
    states[97] = new State(new int[]{56,62},new int[]{-40,98,-41,101,-1,110,-42,111});
    states[98] = new State(new int[]{45,99,42,-46,23,-46,22,-46});
    states[99] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,100,-8,50,-1,61,-6,63,-7,64});
    states[100] = new State(new int[]{6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,38,54,40,55,42,66,44,42,-47,23,-47,22,-47});
    states[101] = new State(new int[]{39,102,37,105,45,-111,42,-111,23,-111,22,-111,38,-111,40,-111},new int[]{-44,104});
    states[102] = new State(new int[]{56,62},new int[]{-1,103});
    states[103] = new State(-110);
    states[104] = new State(-113);
    states[105] = new State(new int[]{56,62},new int[]{-45,106,-40,112,-41,101,-1,110,-42,111});
    states[106] = new State(new int[]{38,107,40,108});
    states[107] = new State(-114);
    states[108] = new State(new int[]{56,62},new int[]{-40,109,-41,101,-1,110,-42,111});
    states[109] = new State(-116);
    states[110] = new State(-109);
    states[111] = new State(-112);
    states[112] = new State(-115);
    states[113] = new State(-50);
    states[114] = new State(-51);
    states[115] = new State(-52);
    states[116] = new State(-53);
    states[117] = new State(new int[]{45,-96,33,-96,39,-96,37,-96,41,-96,46,-96,47,-96,48,-96,49,-96,42,-94,23,-94,22,-94});
    states[118] = new State(new int[]{39,65});
    states[119] = new State(-15);
    states[120] = new State(-16);
    states[121] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,122,-8,50,-1,61,-6,63,-7,64});
    states[122] = new State(new int[]{41,123,6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,38,54,40,55,42,66,44});
    states[123] = new State(new int[]{20,135},new int[]{-30,124});
    states[124] = new State(new int[]{8,126,7,132,42,-86,23,-86,22,-86},new int[]{-27,125,-26,131});
    states[125] = new State(-82);
    states[126] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,127,-8,50,-1,61,-6,63,-7,64});
    states[127] = new State(new int[]{41,128,6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,38,54,40,55,42,66,44});
    states[128] = new State(new int[]{20,135},new int[]{-30,129});
    states[129] = new State(new int[]{8,126,7,132,42,-86,23,-86,22,-86},new int[]{-27,130,-26,131});
    states[130] = new State(-83);
    states[131] = new State(-84);
    states[132] = new State(new int[]{41,133});
    states[133] = new State(new int[]{20,135},new int[]{-30,134});
    states[134] = new State(-85);
    states[135] = new State(new int[]{56,62,29,67,30,68,31,69,32,70,44,71,37,72,6,121,5,141,3,146,25,153,26,157,27,161,28,165,10,169,11,172,12,174,15,176,17,185,24,186,13,191,14,199,23,-5,42,-5},new int[]{-29,136,-22,206,-20,8,-8,9,-1,61,-6,117,-7,118,-19,119,-21,120,-23,139,-24,140,-25,145,-50,152,-51,156,-52,160,-53,164,-14,168,-15,171,-16,173,-17,175,-18,184,-43,190});
    states[136] = new State(new int[]{23,204,42,205},new int[]{-47,137});
    states[137] = new State(new int[]{21,138,56,62,29,67,30,68,31,69,32,70,44,71,37,72,6,121,5,141,3,146,25,153,26,157,27,161,28,165,10,169,11,172,12,174,15,176,17,185,24,186,13,191,14,199,23,-5,42,-5},new int[]{-22,7,-20,8,-8,9,-1,61,-6,117,-7,118,-19,119,-21,120,-23,139,-24,140,-25,145,-50,152,-51,156,-52,160,-53,164,-14,168,-15,171,-16,173,-17,175,-18,184,-43,190});
    states[138] = new State(-104);
    states[139] = new State(-17);
    states[140] = new State(-18);
    states[141] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,142,-8,50,-1,61,-6,63,-7,64});
    states[142] = new State(new int[]{41,143,6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,38,54,40,55,42,66,44});
    states[143] = new State(new int[]{20,135},new int[]{-30,144});
    states[144] = new State(-87);
    states[145] = new State(-19);
    states[146] = new State(new int[]{56,62},new int[]{-1,147});
    states[147] = new State(new int[]{4,148});
    states[148] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77},new int[]{-5,149,-8,50,-1,61,-6,63,-7,64});
    states[149] = new State(new int[]{41,150,6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,38,54,40,55,42,66,44});
    states[150] = new State(new int[]{20,135},new int[]{-30,151});
    states[151] = new State(-88);
    states[152] = new State(-20);
    states[153] = new State(new int[]{41,154});
    states[154] = new State(new int[]{20,135},new int[]{-30,155});
    states[155] = new State(-4);
    states[156] = new State(-21);
    states[157] = new State(new int[]{41,158});
    states[158] = new State(new int[]{20,135},new int[]{-30,159});
    states[159] = new State(-6);
    states[160] = new State(-22);
    states[161] = new State(new int[]{41,162});
    states[162] = new State(new int[]{20,135},new int[]{-30,163});
    states[163] = new State(-8);
    states[164] = new State(-23);
    states[165] = new State(new int[]{41,166});
    states[166] = new State(new int[]{20,135},new int[]{-30,167});
    states[167] = new State(-10);
    states[168] = new State(-24);
    states[169] = new State(new int[]{51,46,65,48,56,62,29,67,30,68,31,69,32,70,44,71,37,72,33,77,42,-91,23,-91,22,-91},new int[]{-5,170,-8,50,-1,61,-6,63,-7,64});
    states[170] = new State(new int[]{6,12,50,16,52,18,53,20,51,22,57,24,58,26,59,28,60,30,61,32,62,34,63,36,64,38,54,40,55,42,66,44,42,-90,23,-90,22,-90});
    states[171] = new State(-25);
    states[172] = new State(-92);
    states[173] = new State(-26);
    states[174] = new State(-93);
    states[175] = new State(-27);
    states[176] = new State(new int[]{56,62},new int[]{-36,177,-2,183,-1,182});
    states[177] = new State(new int[]{40,178,42,-36,23,-36,22,-36});
    states[178] = new State(new int[]{56,62},new int[]{-2,179,-1,182});
    states[179] = new State(new int[]{39,180,40,-41,42,-41,23,-41,22,-41});
    states[180] = new State(new int[]{56,62},new int[]{-1,181});
    states[181] = new State(-39);
    states[182] = new State(-38);
    states[183] = new State(new int[]{39,180,40,-40,42,-40,23,-40,22,-40});
    states[184] = new State(-28);
    states[185] = new State(-35);
    states[186] = new State(new int[]{56,62},new int[]{-4,187,-1,189});
    states[187] = new State(new int[]{20,135},new int[]{-30,188});
    states[188] = new State(-29);
    states[189] = new State(-31);
    states[190] = new State(-30);
    states[191] = new State(new int[]{56,62},new int[]{-38,192,-37,198,-1,195});
    states[192] = new State(new int[]{40,193,42,-32,23,-32,22,-32});
    states[193] = new State(new int[]{56,62},new int[]{-37,194,-1,195});
    states[194] = new State(-45);
    states[195] = new State(new int[]{16,196,40,-43,42,-43,23,-43,22,-43});
    states[196] = new State(new int[]{56,62},new int[]{-1,197});
    states[197] = new State(-42);
    states[198] = new State(-44);
    states[199] = new State(new int[]{56,62},new int[]{-1,200});
    states[200] = new State(new int[]{13,201});
    states[201] = new State(new int[]{52,203,56,62},new int[]{-38,202,-37,198,-1,195});
    states[202] = new State(new int[]{40,193,42,-33,23,-33,22,-33});
    states[203] = new State(-34);
    states[204] = new State(-129);
    states[205] = new State(-130);
    states[206] = new State(-12);
    states[207] = new State(-130);

    rules[1] = new Rule(-54, new int[]{-31,2});
    rules[2] = new Rule(-31, new int[]{-29,-46,22});
    rules[3] = new Rule(-49, new int[]{24,-4,41,-30});
    rules[4] = new Rule(-50, new int[]{25,41,-30});
    rules[5] = new Rule(-50, new int[]{});
    rules[6] = new Rule(-51, new int[]{26,41,-30});
    rules[7] = new Rule(-51, new int[]{});
    rules[8] = new Rule(-52, new int[]{27,41,-30});
    rules[9] = new Rule(-52, new int[]{});
    rules[10] = new Rule(-53, new int[]{28,41,-30});
    rules[11] = new Rule(-53, new int[]{});
    rules[12] = new Rule(-29, new int[]{-22});
    rules[13] = new Rule(-29, new int[]{-29,-47,-22});
    rules[14] = new Rule(-22, new int[]{-20});
    rules[15] = new Rule(-22, new int[]{-19});
    rules[16] = new Rule(-22, new int[]{-21});
    rules[17] = new Rule(-22, new int[]{-23});
    rules[18] = new Rule(-22, new int[]{-24});
    rules[19] = new Rule(-22, new int[]{-25});
    rules[20] = new Rule(-22, new int[]{-50});
    rules[21] = new Rule(-22, new int[]{-51});
    rules[22] = new Rule(-22, new int[]{-52});
    rules[23] = new Rule(-22, new int[]{-53});
    rules[24] = new Rule(-22, new int[]{-14});
    rules[25] = new Rule(-22, new int[]{-15});
    rules[26] = new Rule(-22, new int[]{-16});
    rules[27] = new Rule(-22, new int[]{-17});
    rules[28] = new Rule(-22, new int[]{-18});
    rules[29] = new Rule(-22, new int[]{24,-4,-30});
    rules[30] = new Rule(-22, new int[]{-43});
    rules[31] = new Rule(-4, new int[]{-1});
    rules[32] = new Rule(-43, new int[]{13,-38});
    rules[33] = new Rule(-43, new int[]{14,-1,13,-38});
    rules[34] = new Rule(-43, new int[]{14,-1,13,52});
    rules[35] = new Rule(-18, new int[]{17});
    rules[36] = new Rule(-17, new int[]{15,-36});
    rules[37] = new Rule(-1, new int[]{56});
    rules[38] = new Rule(-2, new int[]{-1});
    rules[39] = new Rule(-2, new int[]{-2,39,-1});
    rules[40] = new Rule(-36, new int[]{-2});
    rules[41] = new Rule(-36, new int[]{-36,40,-2});
    rules[42] = new Rule(-37, new int[]{-1,16,-1});
    rules[43] = new Rule(-37, new int[]{-1});
    rules[44] = new Rule(-38, new int[]{-37});
    rules[45] = new Rule(-38, new int[]{-38,40,-37});
    rules[46] = new Rule(-19, new int[]{-8,41,-40});
    rules[47] = new Rule(-19, new int[]{-8,41,-40,45,-5});
    rules[48] = new Rule(-20, new int[]{-8,45,-5});
    rules[49] = new Rule(-20, new int[]{-8,-48,-5});
    rules[50] = new Rule(-48, new int[]{46});
    rules[51] = new Rule(-48, new int[]{47});
    rules[52] = new Rule(-48, new int[]{48});
    rules[53] = new Rule(-48, new int[]{49});
    rules[54] = new Rule(-5, new int[]{-5,6,-5,7,-5});
    rules[55] = new Rule(-5, new int[]{-5,50,-5});
    rules[56] = new Rule(-5, new int[]{-5,52,-5});
    rules[57] = new Rule(-5, new int[]{-5,53,-5});
    rules[58] = new Rule(-5, new int[]{-5,51,-5});
    rules[59] = new Rule(-5, new int[]{-5,57,-5});
    rules[60] = new Rule(-5, new int[]{-5,58,-5});
    rules[61] = new Rule(-5, new int[]{-5,59,-5});
    rules[62] = new Rule(-5, new int[]{-5,60,-5});
    rules[63] = new Rule(-5, new int[]{-5,61,-5});
    rules[64] = new Rule(-5, new int[]{-5,62,-5});
    rules[65] = new Rule(-5, new int[]{-5,63,-5});
    rules[66] = new Rule(-5, new int[]{-5,64,-5});
    rules[67] = new Rule(-5, new int[]{-5,54,-5});
    rules[68] = new Rule(-5, new int[]{-5,55,-5});
    rules[69] = new Rule(-5, new int[]{-5,66,-5});
    rules[70] = new Rule(-5, new int[]{51,-5});
    rules[71] = new Rule(-5, new int[]{65,-5});
    rules[72] = new Rule(-5, new int[]{-8});
    rules[73] = new Rule(-5, new int[]{-7});
    rules[74] = new Rule(-5, new int[]{33,-5,34});
    rules[75] = new Rule(-7, new int[]{29});
    rules[76] = new Rule(-7, new int[]{30});
    rules[77] = new Rule(-7, new int[]{31});
    rules[78] = new Rule(-7, new int[]{32});
    rules[79] = new Rule(-7, new int[]{44});
    rules[80] = new Rule(-28, new int[]{-5});
    rules[81] = new Rule(-28, new int[]{-28,40,-5});
    rules[82] = new Rule(-21, new int[]{6,-5,41,-30,-27});
    rules[83] = new Rule(-27, new int[]{8,-5,41,-30,-27});
    rules[84] = new Rule(-27, new int[]{-26});
    rules[85] = new Rule(-26, new int[]{7,41,-30});
    rules[86] = new Rule(-26, new int[]{});
    rules[87] = new Rule(-24, new int[]{5,-5,41,-30});
    rules[88] = new Rule(-25, new int[]{3,-1,4,-5,41,-30});
    rules[89] = new Rule(-3, new int[]{-1});
    rules[90] = new Rule(-14, new int[]{10,-5});
    rules[91] = new Rule(-14, new int[]{10});
    rules[92] = new Rule(-15, new int[]{11});
    rules[93] = new Rule(-16, new int[]{12});
    rules[94] = new Rule(-23, new int[]{-6});
    rules[95] = new Rule(-8, new int[]{-1});
    rules[96] = new Rule(-8, new int[]{-6});
    rules[97] = new Rule(-8, new int[]{-8,39,-1});
    rules[98] = new Rule(-8, new int[]{-7,39,-1});
    rules[99] = new Rule(-8, new int[]{37,-28,38});
    rules[100] = new Rule(-8, new int[]{-8,37,-5,38});
    rules[101] = new Rule(-8, new int[]{37,-5,3,-1,4,-5,-9,38});
    rules[102] = new Rule(-9, new int[]{});
    rules[103] = new Rule(-9, new int[]{6,-5});
    rules[104] = new Rule(-30, new int[]{20,-29,-47,21});
    rules[105] = new Rule(-13, new int[]{-39,-30});
    rules[106] = new Rule(-39, new int[]{9,-3,33,-35,34,41});
    rules[107] = new Rule(-39, new int[]{9,-3,33,-35,34,43,-40,41});
    rules[108] = new Rule(-6, new int[]{-8,33,-12,34});
    rules[109] = new Rule(-41, new int[]{-1});
    rules[110] = new Rule(-41, new int[]{-41,39,-1});
    rules[111] = new Rule(-40, new int[]{-41});
    rules[112] = new Rule(-40, new int[]{-42});
    rules[113] = new Rule(-42, new int[]{-41,-44});
    rules[114] = new Rule(-44, new int[]{37,-45,38});
    rules[115] = new Rule(-45, new int[]{-40});
    rules[116] = new Rule(-45, new int[]{-45,40,-40});
    rules[117] = new Rule(-32, new int[]{-1});
    rules[118] = new Rule(-33, new int[]{-32,41,-40});
    rules[119] = new Rule(-34, new int[]{-33});
    rules[120] = new Rule(-34, new int[]{-34,40,-33});
    rules[121] = new Rule(-35, new int[]{-34});
    rules[122] = new Rule(-35, new int[]{});
    rules[123] = new Rule(-10, new int[]{-5});
    rules[124] = new Rule(-10, new int[]{-1,45,-5});
    rules[125] = new Rule(-11, new int[]{-10});
    rules[126] = new Rule(-11, new int[]{-11,40,-10});
    rules[127] = new Rule(-12, new int[]{-11});
    rules[128] = new Rule(-12, new int[]{});
    rules[129] = new Rule(-47, new int[]{23});
    rules[130] = new Rule(-47, new int[]{42});
    rules[131] = new Rule(-46, new int[]{42});
    rules[132] = new Rule(-46, new int[]{});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
      case 2: // program -> stmt_list, optional_semicolon, END_OF_FILE
{
			if (!is_unit_to_be_parsed) {
				var stl = ValueStack[ValueStack.Depth-3].stn as statement_list;
				stl.left_logical_bracket = new token_info("");
				stl.right_logical_bracket = new token_info("");
				var bl = new block(new declarations(), stl, CurrentLocationSpan);
				root = CurrentSemanticValue.stn = NewProgramModule(null, null, new uses_list(), bl, ValueStack[ValueStack.Depth-2].ob, CurrentLocationSpan);
				root.source_context = bl.source_context;
			}
			else {
				var interface_part = new interface_node(new declarations(), new uses_list(), null, null);
				var initialization_part = new initfinal_part(null, ValueStack[ValueStack.Depth-3].stn as statement_list, null, null, null, CurrentLocationSpan);

				root = CurrentSemanticValue.stn = new unit_module(
					new unit_name(new ident(Path.GetFileNameWithoutExtension(parserTools.currentFileName)),
					UnitHeaderKeyword.Unit, CurrentLocationSpan), interface_part, null,
					initialization_part.initialization_sect,
					initialization_part.finalization_sect, null, CurrentLocationSpan);
			}

		}
        break;
      case 3: // task_definition -> TASK, task_id, COLON, block
{
	CurrentSemanticValue.stn = new task_stmt(
		ValueStack[ValueStack.Depth-3].id as ident, 
		ValueStack[ValueStack.Depth-1].stn as statement_list,
		CurrentLocationSpan
	);
    }
        break;
      case 4: // input_section -> INPUT, COLON, block
{
          CurrentSemanticValue.stn = new input_section(ValueStack[ValueStack.Depth-1].stn as statement_list);
      }
        break;
      case 5: // input_section -> /* empty */
{
          CurrentSemanticValue.stn = null;
      }
        break;
      case 6: // check_section -> CHECK, COLON, block
{ 
                CurrentSemanticValue.stn = new check_section(ValueStack[ValueStack.Depth-1].stn as statement_list);
      }
        break;
      case 7: // check_section -> /* empty */
{ CurrentSemanticValue.stn = null; }
        break;
      case 8: // tests_section -> TESTS, COLON, block
{ 
                CurrentSemanticValue.stn = new tests_section(ValueStack[ValueStack.Depth-1].stn as statement_list);
      }
        break;
      case 9: // tests_section -> /* empty */
{ CurrentSemanticValue.stn = null; }
        break;
      case 10: // output_section -> OUTPUT, COLON, block
{ 
                CurrentSemanticValue.stn = new output_section(ValueStack[ValueStack.Depth-1].stn as statement_list);
      }
        break;
      case 11: // output_section -> /* empty */
{ CurrentSemanticValue.stn = null; }
        break;
      case 12: // stmt_list -> stmt
{
			CurrentSemanticValue.stn = new statement_list(ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan);
		}
        break;
      case 13: // stmt_list -> stmt_list, end_of_line, stmt
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as statement_list).Add(ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan);
		}
        break;
      case 14: // stmt -> assign_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 15: // stmt -> var_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 16: // stmt -> if_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 17: // stmt -> proc_func_call_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 18: // stmt -> while_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 19: // stmt -> for_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 20: // stmt -> input_section
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 21: // stmt -> check_section
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 22: // stmt -> tests_section
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 23: // stmt -> output_section
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 24: // stmt -> return_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 25: // stmt -> break_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 26: // stmt -> continue_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 27: // stmt -> global_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 28: // stmt -> pass_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 29: // stmt -> TASK, task_id, block
{
			var file_type = new named_type_reference(new ident("str"));
			var file_name = new typed_parameters(new ident_list(ValueStack[ValueStack.Depth-2].id), file_type, parametr_kind.none, null);
			var file_name_param = new formal_parameters(file_name, CurrentLocationSpan);

			var func_name = new ident("CheckTaskT");

			var proc_head = new procedure_header(
				file_name_param as formal_parameters, 
				new procedure_attributes_list(new List<procedure_attribute>()), 
				new method_name(null,null, func_name, null), 
				null, 
				CurrentLocationSpan
			);
			var proc_def = new procedure_definition(proc_head, new block(null, ValueStack[ValueStack.Depth-1].stn as statement_list, LocationStack[LocationStack.Depth-1]), CurrentLocationSpan);
			CurrentSemanticValue.stn = new declarations_as_statement(new declarations(proc_def, CurrentLocationSpan), CurrentLocationSpan);
		}
        break;
      case 30: // stmt -> import_clause
{
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 31: // task_id -> ident
{ CurrentSemanticValue.id = new ident(ValueStack[ValueStack.Depth-1].id.name); }
        break;
      case 32: // import_clause -> IMPORT, ident_as_ident_list
{
			CurrentSemanticValue.stn = new import_statement(ValueStack[ValueStack.Depth-1].stn as as_statement_list, CurrentLocationSpan);
		}
        break;
      case 33: // import_clause -> FROM, ident, IMPORT, ident_as_ident_list
{
			CurrentSemanticValue.stn = new from_import_statement(ValueStack[ValueStack.Depth-3].id as ident, false, ValueStack[ValueStack.Depth-1].stn as as_statement_list, CurrentLocationSpan);
		}
        break;
      case 34: // import_clause -> FROM, ident, IMPORT, STAR
{
			CurrentSemanticValue.stn = new from_import_statement(ValueStack[ValueStack.Depth-3].id as ident, true, null, CurrentLocationSpan);
		}
        break;
      case 35: // pass_stmt -> PASS
{
			CurrentSemanticValue.stn = new empty_statement();
		}
        break;
      case 36: // global_stmt -> GLOBAL, dotted_ident_list
{
			CurrentSemanticValue.stn = new global_statement(ValueStack[ValueStack.Depth-1].stn as ident_list, CurrentLocationSpan);
		}
        break;
      case 37: // ident -> ID
{
			CurrentSemanticValue.id = ValueStack[ValueStack.Depth-1].id;
		}
        break;
      case 38: // dotted_ident -> ident
{ 
			CurrentSemanticValue.id = ValueStack[ValueStack.Depth-1].id; 
		}
        break;
      case 39: // dotted_ident -> dotted_ident, DOT, ident
{ 
			CurrentSemanticValue.id = new ident(ValueStack[ValueStack.Depth-3].id.name + "." + ValueStack[ValueStack.Depth-1].id.name, CurrentLocationSpan); 
		}
        break;
      case 40: // dotted_ident_list -> dotted_ident
{
			CurrentSemanticValue.stn = new ident_list(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 41: // dotted_ident_list -> dotted_ident_list, COMMA, dotted_ident
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as ident_list).Add(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 42: // ident_as_ident -> ident, AS, ident
{ 
			CurrentSemanticValue.stn = new as_statement(ValueStack[ValueStack.Depth-3].id, ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan); 
		}
        break;
      case 43: // ident_as_ident -> ident
{ 
			CurrentSemanticValue.stn = new as_statement(ValueStack[ValueStack.Depth-1].id, ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan); 
		}
        break;
      case 44: // ident_as_ident_list -> ident_as_ident
{
			CurrentSemanticValue.stn = new as_statement_list(ValueStack[ValueStack.Depth-1].stn as as_statement, CurrentLocationSpan);
		}
        break;
      case 45: // ident_as_ident_list -> ident_as_ident_list, COMMA, ident_as_ident
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as as_statement_list).Add(ValueStack[ValueStack.Depth-1].stn as as_statement, CurrentLocationSpan);
		}
        break;
      case 46: // var_stmt -> variable, COLON, type_ref
{
			var vds = new var_def_statement(new ident_list(ValueStack[ValueStack.Depth-3].ex as ident, LocationStack[LocationStack.Depth-3]), ValueStack[ValueStack.Depth-1].td, null, definition_attribute.None, false, CurrentLocationSpan);
			CurrentSemanticValue.stn = new var_statement(vds, CurrentLocationSpan);
		}
        break;
      case 47: // var_stmt -> variable, COLON, type_ref, ASSIGN, expr
{
			var vds = new var_def_statement(new ident_list(ValueStack[ValueStack.Depth-5].ex as ident, LocationStack[LocationStack.Depth-5]), ValueStack[ValueStack.Depth-3].td, ValueStack[ValueStack.Depth-1].ex, definition_attribute.None, false, CurrentLocationSpan);
			CurrentSemanticValue.stn = new var_statement(vds, CurrentLocationSpan);
		}
        break;
      case 48: // assign_stmt -> variable, ASSIGN, expr
{
			if (!(ValueStack[ValueStack.Depth-3].ex is addressed_value))
        		parserTools.AddErrorFromResource("LEFT_SIDE_CANNOT_BE_ASSIGNED_TO", CurrentLocationSpan);
			CurrentSemanticValue.stn = new assign(ValueStack[ValueStack.Depth-3].ex as addressed_value, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan);
		}
        break;
      case 49: // assign_stmt -> variable, assign_type, expr
{
			if (!(ValueStack[ValueStack.Depth-3].ex is addressed_value))
        		parserTools.AddErrorFromResource("LEFT_SIDE_CANNOT_BE_ASSIGNED_TO", CurrentLocationSpan);
			CurrentSemanticValue.stn = new assign(ValueStack[ValueStack.Depth-3].ex as addressed_value, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan);
		}
        break;
      case 50: // assign_type -> PLUSEQUAL
{ 
			CurrentSemanticValue.op = ValueStack[ValueStack.Depth-1].op; 
		}
        break;
      case 51: // assign_type -> MINUSEQUAL
{ 
			CurrentSemanticValue.op = ValueStack[ValueStack.Depth-1].op; 
		}
        break;
      case 52: // assign_type -> STAREQUAL
{ 
			CurrentSemanticValue.op = ValueStack[ValueStack.Depth-1].op; 
		}
        break;
      case 53: // assign_type -> DIVEQUAL
{ 
			CurrentSemanticValue.op = ValueStack[ValueStack.Depth-1].op; 
		}
        break;
      case 54: // expr -> expr, IF, expr, ELSE, expr
{
			CurrentSemanticValue.ex = new question_colon_expression(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-5].ex, ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 55: // expr -> expr, PLUS, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 56: // expr -> expr, STAR, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 57: // expr -> expr, DIVIDE, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 58: // expr -> expr, MINUS, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 59: // expr -> expr, LESS, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 60: // expr -> expr, GREATER, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 61: // expr -> expr, LESSEQUAL, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 62: // expr -> expr, GREATEREQUAL, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 63: // expr -> expr, EQUAL, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 64: // expr -> expr, NOTEQUAL, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 65: // expr -> expr, AND, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 66: // expr -> expr, OR, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 67: // expr -> expr, SLASHSLASH, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 68: // expr -> expr, PERCENTAGE, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 69: // expr -> expr, STARSTAR, expr
{
			addressed_value method_name = new ident("!pow", CurrentLocationSpan);
			expression_list el = new expression_list(new List<expression> { ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex }, CurrentLocationSpan);
			CurrentSemanticValue.ex = new method_call(method_name, el, CurrentLocationSpan);
		}
        break;
      case 70: // expr -> MINUS, expr
{ 
			CurrentSemanticValue.ex = new un_expr(ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 71: // expr -> NOT, expr
{ 
			CurrentSemanticValue.ex = new un_expr(ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 72: // expr -> variable
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 73: // expr -> const_value
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 74: // expr -> LPAR, expr, RPAR
{ 
			CurrentSemanticValue.ex = new bracket_expr(ValueStack[ValueStack.Depth-2].ex, CurrentLocationSpan); 
		}
        break;
      case 75: // const_value -> INTNUM
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 76: // const_value -> REALNUM
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 77: // const_value -> TRUE
{ 
			CurrentSemanticValue.ex = new ident("true", CurrentLocationSpan); 
		}
        break;
      case 78: // const_value -> FALSE
{ 
			CurrentSemanticValue.ex = new ident("false", CurrentLocationSpan); 
		}
        break;
      case 79: // const_value -> STRINGNUM
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].stn as literal; 
		}
        break;
      case 80: // expr_list -> expr
{
			CurrentSemanticValue.stn = new expression_list(ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 81: // expr_list -> expr_list, COMMA, expr
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as expression_list).Add(ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 82: // if_stmt -> IF, expr, COLON, block, optional_elif
{
			CurrentSemanticValue.stn = new if_node(ValueStack[ValueStack.Depth-4].ex, ValueStack[ValueStack.Depth-2].stn as statement, ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan);
		}
        break;
      case 83: // optional_elif -> ELIF, expr, COLON, block, optional_elif
{
			CurrentSemanticValue.stn = new if_node(ValueStack[ValueStack.Depth-4].ex, ValueStack[ValueStack.Depth-2].stn as statement, ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan);
		}
        break;
      case 84: // optional_elif -> optional_else
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 85: // optional_else -> ELSE, COLON, block
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 86: // optional_else -> /* empty */
{ 
			CurrentSemanticValue.stn = null; 
		}
        break;
      case 87: // while_stmt -> WHILE, expr, COLON, block
{
			CurrentSemanticValue.stn = new while_node(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].stn as statement, WhileCycleType.While, CurrentLocationSpan);
		}
        break;
      case 88: // for_stmt -> FOR, ident, IN, expr, COLON, block
{
			CurrentSemanticValue.stn = new foreach_stmt(ValueStack[ValueStack.Depth-5].id, new no_type_foreach(), ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].stn as statement, null, CurrentLocationSpan);
		}
        break;
      case 89: // func_name_ident -> ident
{
			CurrentSemanticValue.id = ValueStack[ValueStack.Depth-1].id;
		}
        break;
      case 90: // return_stmt -> RETURN, expr
{
			statement res_assign = new assign(new ident("result"), ValueStack[ValueStack.Depth-1].ex, Operators.Assignment, CurrentLocationSpan);
			statement exit_call = new procedure_call(new ident("exit"), true, CurrentLocationSpan);
			CurrentSemanticValue.stn = new statement_list(res_assign, CurrentLocationSpan);
			(CurrentSemanticValue.stn as statement_list).Add(exit_call, CurrentLocationSpan);
		}
        break;
      case 91: // return_stmt -> RETURN
{
			CurrentSemanticValue.stn = new procedure_call(new ident("exit", CurrentLocationSpan), true, CurrentLocationSpan);
		}
        break;
      case 92: // break_stmt -> BREAK
{
			CurrentSemanticValue.stn = new procedure_call(new ident("break", CurrentLocationSpan), true, CurrentLocationSpan);
		}
        break;
      case 93: // continue_stmt -> CONTINUE
{
			CurrentSemanticValue.stn = new procedure_call(new ident("continue", CurrentLocationSpan), true, CurrentLocationSpan);
		}
        break;
      case 94: // proc_func_call_stmt -> proc_func_call
{
			CurrentSemanticValue.stn = new procedure_call(ValueStack[ValueStack.Depth-1].ex as addressed_value, ValueStack[ValueStack.Depth-1].ex is ident, CurrentLocationSpan);
		}
        break;
      case 95: // variable -> ident
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].id; 
		}
        break;
      case 96: // variable -> proc_func_call
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 97: // variable -> variable, DOT, ident
{ 
			CurrentSemanticValue.ex = new dot_node(ValueStack[ValueStack.Depth-3].ex as addressed_value, ValueStack[ValueStack.Depth-1].id as addressed_value, CurrentLocationSpan); 
		}
        break;
      case 98: // variable -> const_value, DOT, ident
{ 
			CurrentSemanticValue.ex = new dot_node(ValueStack[ValueStack.Depth-3].ex as addressed_value, ValueStack[ValueStack.Depth-1].id as addressed_value, CurrentLocationSpan); 
		}
        break;
      case 99: // variable -> LBRACKET, expr_list, RBRACKET
{
			var acn = new array_const_new(ValueStack[ValueStack.Depth-2].stn as expression_list, '|', CurrentLocationSpan);
//			var dn = new dot_node(acn as addressed_value, (new ident("ToList", @$)) as addressed_value, @$);
			CurrentSemanticValue.ex = acn;
		}
        break;
      case 100: // variable -> variable, LBRACKET, expr, RBRACKET
{
			var el = new expression_list(ValueStack[ValueStack.Depth-2].ex as expression, CurrentLocationSpan);
			CurrentSemanticValue.ex = new indexer(ValueStack[ValueStack.Depth-4].ex as addressed_value, el, CurrentLocationSpan);
		}
        break;
      case 101: // variable -> LBRACKET, expr, FOR, ident, IN, expr, optional_condition, RBRACKET
{
			CurrentSemanticValue.ex = new list_generator(ValueStack[ValueStack.Depth-7].ex, ValueStack[ValueStack.Depth-5].id, ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-2].ex, CurrentLocationSpan);
		}
        break;
      case 102: // optional_condition -> /* empty */
{ 
			CurrentSemanticValue.ex = null; 
		}
        break;
      case 103: // optional_condition -> IF, expr
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 104: // block -> INDENT, stmt_list, end_of_line, UNINDENT
{
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-3].stn as statement_list;
			(CurrentSemanticValue.stn as statement_list).left_logical_bracket = ValueStack[ValueStack.Depth-4].ti;
			(CurrentSemanticValue.stn as statement_list).right_logical_bracket = ValueStack[ValueStack.Depth-1].ti;
			CurrentSemanticValue.stn.source_context = LexLocation.MergeAll(LocationStack[LocationStack.Depth-3], LocationStack[LocationStack.Depth-2]);
		}
        break;
      case 105: // proc_func_decl -> proc_func_header, block
{
			CurrentSemanticValue.stn = new procedure_definition(ValueStack[ValueStack.Depth-2].td as procedure_header, new block(null, ValueStack[ValueStack.Depth-1].stn as statement_list, LocationStack[LocationStack.Depth-1]), CurrentLocationSpan);
		}
        break;
      case 106: // proc_func_header -> DEF, func_name_ident, LPAR, optional_form_param_list, RPAR, 
                //                     COLON
{
			CurrentSemanticValue.td = new procedure_header(ValueStack[ValueStack.Depth-3].stn as formal_parameters, new procedure_attributes_list(new List<procedure_attribute>()), new method_name(null,null, ValueStack[ValueStack.Depth-5].id, null, LocationStack[LocationStack.Depth-5]), null, CurrentLocationSpan);
		}
        break;
      case 107: // proc_func_header -> DEF, func_name_ident, LPAR, optional_form_param_list, RPAR, 
                //                     ARROW, type_ref, COLON
{
			CurrentSemanticValue.td = new function_header(ValueStack[ValueStack.Depth-5].stn as formal_parameters, new procedure_attributes_list(new List<procedure_attribute>()), new method_name(null,null, ValueStack[ValueStack.Depth-7].id, null, LocationStack[LocationStack.Depth-7]), null, ValueStack[ValueStack.Depth-2].td as type_definition, CurrentLocationSpan);
		}
        break;
      case 108: // proc_func_call -> variable, LPAR, optional_act_param_list, RPAR
{
			CurrentSemanticValue.ex = new method_call(ValueStack[ValueStack.Depth-4].ex as addressed_value, ValueStack[ValueStack.Depth-2].stn as expression_list, CurrentLocationSpan);
		}
        break;
      case 109: // simple_type_identifier -> ident
{
			CurrentSemanticValue.td = new named_type_reference(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 110: // simple_type_identifier -> simple_type_identifier, DOT, ident
{ 
			CurrentSemanticValue.td = (ValueStack[ValueStack.Depth-3].td as named_type_reference).Add(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 111: // type_ref -> simple_type_identifier
{
			CurrentSemanticValue.td = ValueStack[ValueStack.Depth-1].td as named_type_reference;
		}
        break;
      case 112: // type_ref -> template_type
{ 
			CurrentSemanticValue.td = ValueStack[ValueStack.Depth-1].td; 
		}
        break;
      case 113: // template_type -> simple_type_identifier, template_type_params
{ 
			CurrentSemanticValue.td = new template_type_reference(ValueStack[ValueStack.Depth-2].td as named_type_reference, ValueStack[ValueStack.Depth-1].stn as template_param_list, CurrentLocationSpan); 
		}
        break;
      case 114: // template_type_params -> LBRACKET, template_param_list, RBRACKET
{
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-2].stn;
			CurrentSemanticValue.stn.source_context = CurrentLocationSpan;
		}
        break;
      case 115: // template_param_list -> type_ref
{ 
			CurrentSemanticValue.stn = new template_param_list(ValueStack[ValueStack.Depth-1].td, CurrentLocationSpan);
		}
        break;
      case 116: // template_param_list -> template_param_list, COMMA, type_ref
{ 
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as template_param_list).Add(ValueStack[ValueStack.Depth-1].td, CurrentLocationSpan);
		}
        break;
      case 117: // param_name -> ident
{
			CurrentSemanticValue.stn = new ident_list(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 118: // form_param_sect -> param_name, COLON, type_ref
{
			CurrentSemanticValue.stn = new typed_parameters(ValueStack[ValueStack.Depth-3].stn as ident_list, ValueStack[ValueStack.Depth-1].td, parametr_kind.none, null, CurrentLocationSpan);
		}
        break;
      case 119: // form_param_list -> form_param_sect
{
			CurrentSemanticValue.stn = new formal_parameters(ValueStack[ValueStack.Depth-1].stn as typed_parameters, CurrentLocationSpan);
        }
        break;
      case 120: // form_param_list -> form_param_list, COMMA, form_param_sect
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as formal_parameters).Add(ValueStack[ValueStack.Depth-1].stn as typed_parameters, CurrentLocationSpan);
        }
        break;
      case 121: // optional_form_param_list -> form_param_list
{
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn;
		}
        break;
      case 122: // optional_form_param_list -> /* empty */
{
			CurrentSemanticValue.stn = null;
		}
        break;
      case 123: // act_param -> expr
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 124: // act_param -> ident, ASSIGN, expr
{ 
			CurrentSemanticValue.ex = new name_assign_expr(ValueStack[ValueStack.Depth-3].id, ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan); 
		}
        break;
      case 125: // act_param_list -> act_param
{
			CurrentSemanticValue.stn = new expression_list(ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 126: // act_param_list -> act_param_list, COMMA, act_param
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as expression_list).Add(ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 127: // optional_act_param_list -> act_param_list
{
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn;
		}
        break;
      case 128: // optional_act_param_list -> /* empty */
{
			CurrentSemanticValue.stn = null;
		}
        break;
      case 129: // end_of_line -> END_OF_LINE
{
			CurrentSemanticValue.ob = ValueStack[ValueStack.Depth-1].ti;
		}
        break;
      case 130: // end_of_line -> SEMICOLON
{
			CurrentSemanticValue.ob = ValueStack[ValueStack.Depth-1].ti;
		}
        break;
      case 131: // optional_semicolon -> SEMICOLON
{ CurrentSemanticValue.ob = ValueStack[ValueStack.Depth-1].ti; }
        break;
      case 132: // optional_semicolon -> /* empty */
{ CurrentSemanticValue.ob = null; }
        break;
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

/* ---------------------- Ð?Ð¡Ð?Ð?Ð?Ð?Ð?ÐÐ¢Ð?Ð?Ð¬ÐÐ«Ð? Ð?Ð?Ð¢Ð?Ð? ---------------------- */
public program_module NewProgramModule(program_name progName, Object optHeadCompDirs, uses_list mainUsesClose, syntax_tree_node progBlock, Object optPoint, LexLocation loc)
{
    var progModule = new program_module(progName, mainUsesClose, progBlock as block, null, loc);
    progModule.Language = "SLang";
    if (optPoint == null && progBlock != null)
    {
        var fp = progBlock.source_context.end_position;
        var err_stn = progBlock;
		if ((progBlock is block) && (progBlock as block).program_code != null && (progBlock as block).program_code.subnodes != null && (progBlock as block).program_code.subnodes.Count > 0)
            err_stn = (progBlock as block).program_code.subnodes[(progBlock as block).program_code.subnodes.Count - 1];
    }
    return progModule;
}
}
}
