<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net40</TargetFramework>
    
    <RootNamespace>Languages.SLang.Frontend.Wrapping</RootNamespace>
    
    <OutputPath>..\..\..\bin\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Errors\Errors.csproj" />
    <ProjectReference Include="..\..\..\LanguageIntegrator\LanguageIntegrator.csproj" />
    <ProjectReference Include="..\..\..\Localization\Localization.csproj" />
    <ProjectReference Include="..\..\..\ParserTools\ParserTools.csproj" />
    <ProjectReference Include="..\..\..\SyntaxTree\SyntaxTree.csproj" />
    <ProjectReference Include="..\..\..\SyntaxVisitors\SyntaxVisitors.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\..\..\..\..\Downloads\Olymp-2 (1)\db.txt">
      <Link>examples\Olymp-2 (1)\db.txt</Link>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Olymp-2 (1)\lightpt.dat">
      <Link>examples\Olymp-2 (1)\lightpt.dat</Link>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Olymp-2 (1)\Oly2.pdf">
      <Link>examples\Olymp-2 (1)\Oly2.pdf</Link>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Olymp-2 (1)\Olymp2-Task01.pas">
      <Link>examples\Olymp-2 (1)\Olymp2-Task01.pas</Link>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Olymp-2 (1)\Olymp2-Task02.pas">
      <Link>examples\Olymp-2 (1)\Olymp2-Task02.pas</Link>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Olymp-2 (1)\Olymp2-Task03.pas">
      <Link>examples\Olymp-2 (1)\Olymp2-Task03.pas</Link>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Olymp-2 (1)\Olymp2-Task04.pas">
      <Link>examples\Olymp-2 (1)\Olymp2-Task04.pas</Link>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Olymp-2 (1)\Olymp2-Task05.pas">
      <Link>examples\Olymp-2 (1)\Olymp2-Task05.pas</Link>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Olymp-2 (1)\Olymp2-Task06.pas">
      <Link>examples\Olymp-2 (1)\Olymp2-Task06.pas</Link>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Olymp-2 (1)\Olymp2-Task07.pas">
      <Link>examples\Olymp-2 (1)\Olymp2-Task07.pas</Link>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Olymp-2 (1)\Olymp2-Task08.pas">
      <Link>examples\Olymp-2 (1)\Olymp2-Task08.pas</Link>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Olymp-2 (1)\Olymp2-Task09.pas">
      <Link>examples\Olymp-2 (1)\Olymp2-Task09.pas</Link>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Olymp-2 (1)\olympFullExample.pas">
      <Link>examples\Olymp-2 (1)\olympFullExample.pas</Link>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Olymp-2 (1)\server.dat">
      <Link>examples\Olymp-2 (1)\server.dat</Link>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Olymp-2 (1)\Tasks.pas">
      <Link>examples\Olymp-2 (1)\Tasks.pas</Link>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Olymp-2 (1)\TasksOlymp1.pas">
      <Link>examples\Olymp-2 (1)\TasksOlymp1.pas</Link>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Olymp-2 (1)\Tree.txt">
      <Link>examples/Olymp-2 (1)/Tree.txt</Link>
    </Content>
    <Content Include="..\..\..\bin\Highlighting\SLang.xshd">
      <Link>SLang.xshd</Link>
    </Content>
    <Content Include="..\..\..\bin\Lib\LightPT.pas">
      <Link>examples\LightPT.pas</Link>
    </Content>
    <Content Include="examples\DSLExample.slang" />
    <Content Include="examples\InputCode.slang" />
    <Content Include="examples\LightPT.txt" />
    <Content Include="examples\Olymp2-Task01.pas">
      <Link>examples\Olymp-2 (1)\Olymp2-Task01.pas</Link>
    </Content>
    <Content Include="examples\Olymp\lightpt.dat" />
    <Content Include="examples\Olymp\Oly2.pdf" />
    <Content Include="examples\Olymp\Olymp2-Task01.pas" />
    <Content Include="examples\Olymp\Olymp2-Task02.pas" />
    <Content Include="examples\Olymp\Olymp2-Task03.pas" />
    <Content Include="examples\Olymp\Olymp2-Task04.pas" />
    <Content Include="examples\Olymp\Olymp2-Task05.pas" />
    <Content Include="examples\Olymp\Olymp2-Task06.pas" />
    <Content Include="examples\Olymp\Olymp2-Task07.pas" />
    <Content Include="examples\Olymp\Olymp2-Task08.pas" />
    <Content Include="examples\Olymp\Olymp2-Task09.pas" />
    <Content Include="examples\Olymp\server.dat" />
    <Content Include="examples\Olymp\Tasks.pas" />
    <Content Include="examples\Olymp\TasksOlymp1.pas" />
    <Content Include="gps.sh" />
    <Content Include="SLangLexer.lex" />
    <Content Include="SLangParser.y" />
  </ItemGroup>
</Project>
