// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.3.6
// Machine:  DESKTOP-56159VE
// DateTime: 27.10.2023 20:45:35
// UserName: ????
// Input file <PythonYacc.y>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using System.IO;
using PythonProgramTree;

namespace PythonParser
{
public enum Tokens {
    error=1,EOF=2,INDENT=3,UNINDENT=4,STUFF=5,REST=6};

public struct ValueType
{ 
			public double dVal; 
			public int iVal; 
			public string sVal; 
			public Node nVal;
			public ExprNode eVal;
			public StatementNode stVal;
			public BlockNode blVal;
       }
// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
  // Verbatim content from PythonYacc.y
    public Parser(AbstractScanner<ValueType, LexLocation> scanner) : base(scanner) { }
  // End verbatim content from PythonYacc.y

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[8];
  private static State[] states = new State[9];
  private static string[] nonTerms = new string[] {
      "root", "stuff", "$accept", };

  static Parser() {
    states[0] = new State(new int[]{5,4,3,6,4,7},new int[]{-1,1,-2,8});
    states[1] = new State(new int[]{2,2,5,4,3,6,4,7},new int[]{-2,3});
    states[2] = new State(-1);
    states[3] = new State(-2);
    states[4] = new State(new int[]{6,5,2,-4,5,-4,3,-4,4,-4});
    states[5] = new State(-5);
    states[6] = new State(-6);
    states[7] = new State(-7);
    states[8] = new State(-3);

    rules[1] = new Rule(-3, new int[]{-1,2});
    rules[2] = new Rule(-1, new int[]{-1,-2});
    rules[3] = new Rule(-1, new int[]{-2});
    rules[4] = new Rule(-2, new int[]{5});
    rules[5] = new Rule(-2, new int[]{5,6});
    rules[6] = new Rule(-2, new int[]{3});
    rules[7] = new Rule(-2, new int[]{4});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
      case 4: // stuff -> STUFF
{ Console.WriteLine("STUFF"); }
        break;
      case 5: // stuff -> STUFF, REST
{ Console.WriteLine("STUFF REST"); }
        break;
      case 6: // stuff -> INDENT
{ Console.WriteLine("INDENT"); }
        break;
      case 7: // stuff -> UNINDENT
{ Console.WriteLine("UNINDENT"); }
        break;
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }


}
}
